# Generated by Django 5.2.7 on 2025-10-23 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_guardian_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_private_teacher',
            field=models.BooleanField(default=False, help_text='Designates if this user can access private teaching teacher features'),
        ),
    ]
