# Generated by Django 5.2.7 on 2025-10-23 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_is_private_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Teacher biography displayed on profile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='specializations',
            field=models.TextField(blank=True, help_text='Musical specializations and expertise'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='teaching_experience',
            field=models.TextField(blank=True, help_text='Teaching experience and qualifications'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='website',
            field=models.URLField(blank=True, help_text="Teacher's personal or professional website"),
        ),
    ]
