# Generated by Django 5.2.7 on 2025-10-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_bio_userprofile_specializations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_zoom_link',
            field=models.URLField(blank=True, help_text='Default Zoom link for online lessons'),
        ),
    ]
