# Generated by Django 5.2.7 on 2025-10-28 14:07

from django.db import migrations, models


def set_existing_users_as_students(apps, schema_editor):
    """
    Set is_student=True for all existing profiles that aren't teachers.
    This ensures existing users get the new default behavior.
    """
    UserProfile = apps.get_model('accounts', 'UserProfile')

    # Update all profiles that aren't teachers to be students
    profiles_updated = UserProfile.objects.filter(
        is_student=False,
        is_teacher=False
    ).update(is_student=True)

    print(f"✅ Set {profiles_updated} existing user(s) as students")


def reverse_set_students(apps, schema_editor):
    """Reverse migration - no action needed"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_sync_instructor_to_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_student',
            field=models.BooleanField(default=True, help_text='Students can enroll in courses, workshops, and request private lessons'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_teacher',
            field=models.BooleanField(default=False, help_text='Teachers can create courses, workshops, and offer private lessons'),
        ),
        migrations.RunPython(set_existing_users_as_students, reverse_set_students),
    ]
