# Generated by Django 5.2.7 on 2025-10-28 18:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_set_student_default_true'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='guardian_email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='guardian_first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='guardian_last_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='guardian_phone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='under_eighteen',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_guardian',
            field=models.BooleanField(default=False, help_text='Guardian/parent managing child profiles (under 18)'),
        ),
        migrations.CreateModel(
            name='ChildProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text="Child's first name", max_length=100)),
                ('last_name', models.CharField(help_text="Child's last name (needed for exam registration)", max_length=100)),
                ('date_of_birth', models.DateField(help_text="Child's date of birth for age calculation")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guardian', models.ForeignKey(help_text="Parent/guardian who manages this child's account", on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Child Profile',
                'verbose_name_plural': 'Child Profiles',
                'ordering': ['first_name', 'last_name'],
            },
        ),
    ]
