# Generated by Django 5.2.7 on 2025-10-29 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_child_profile_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='accepting_new_private_students',
            field=models.BooleanField(default=True, help_text='Whether this teacher is currently accepting new private teaching students'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='max_private_students',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of private teaching students this teacher can accept', null=True),
        ),
    ]
