# Generated by Django 5.2.7 on 2025-11-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_accepting_new_private_students_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_on_new_message',
            field=models.BooleanField(default=True, help_text='Send email notification when you receive a new message'),
        ),
    ]
