# Generated by Django 5.2.7 on 2025-11-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_userprofile_email_on_new_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='age_groups_taught',
            field=models.CharField(blank=True, help_text='Age groups you teach (e.g., Children 5-12, Teens, Adults)', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dbs_check_status',
            field=models.CharField(blank=True, choices=[('current', 'Current DBS Check'), ('in_progress', 'DBS Check In Progress'), ('equivalent', 'Equivalent Background Check'), ('none', 'No DBS Check')], help_text='Required for teaching children in the UK', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='exam_boards_offered',
            field=models.CharField(blank=True, help_text='Exam boards you prepare students for (e.g., Trinity, ABRSM, Rock School)', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='instruments_taught',
            field=models.TextField(blank=True, help_text='Instruments and levels you teach (e.g., Recorder: Beginner to Grade 8)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='professional_memberships',
            field=models.CharField(blank=True, help_text="Professional organizations (e.g., Musicians' Union, ISM)", max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='qualifications',
            field=models.TextField(blank=True, help_text='Degrees, diplomas, certifications (one per line)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='teaching_philosophy',
            field=models.TextField(blank=True, help_text='Your approach to teaching music'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='specializations',
            field=models.TextField(blank=True, help_text='Musical specializations and expertise (legacy)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='teaching_experience',
            field=models.TextField(blank=True, help_text='Teaching experience and qualifications (legacy)'),
        ),
    ]
