# Generated by Django 5.2.7 on 2025-12-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_is_private_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='workshop_email_notifications',
            field=models.BooleanField(default=True, help_text="Receive email notifications about workshops you're registered for"),
        ),
    ]
