# Generated by Django 5.2.9 on 2026-04-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_userprofile_workshop_email_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='lesson_reminder_notifications',
            field=models.BooleanField(default=True, help_text='Receive reminder emails before your scheduled private lessons'),
        ),
    ]
