# Generated by Django 5.2.7 on 2025-11-14 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_userprofile_email_on_new_message'),
        ('courses', '0010_coursemessage_is_read'),
        ('messaging', '0001_initial'),
        ('workshops', '0017_alter_workshopregistration_child_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Course this conversation is about (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='domain',
            field=models.CharField(choices=[('workshop', 'Workshop'), ('course', 'Course'), ('private_teaching', 'Private Teaching')], db_index=True, max_length=30),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['course', '-updated_at'], name='messaging_c_course__315f66_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('domain', 'course')), fields=('course', 'participant_1', 'participant_2'), name='unique_course_conversation'),
        ),
    ]
