# Generated by Django 5.2.9 on 2026-01-02 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_userprofile_workshop_email_notifications'),
        ('courses', '0020_add_content_rating'),
        ('messaging', '0002_add_course_messaging'),
        ('private_teaching', '0023_add_max_recurring_lessons'),
        ('workshops', '0028_merge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='conversation',
            name='unique_private_teaching_conversation',
        ),
        migrations.AddField(
            model_name='conversation',
            name='private_lesson_assignment',
            field=models.ForeignKey(blank=True, help_text='Assignment this conversation is about (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='private_teaching.privatelessonassignment'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['private_lesson_assignment', '-updated_at'], name='messaging_c_private_5d9f16_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('domain', 'private_teaching'), ('private_lesson_assignment__isnull', True)), fields=('participant_1', 'participant_2', 'child_profile'), name='unique_private_teaching_conversation'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('domain', 'private_teaching'), ('private_lesson_assignment__isnull', False)), fields=('private_lesson_assignment', 'participant_1', 'participant_2'), name='unique_assignment_conversation'),
        ),
    ]
