# Generated by Django 5.2.9 on 2026-02-23 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_userprofile_workshop_email_notifications'),
        ('messaging', '0003_remove_conversation_unique_private_teaching_conversation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='child_profile',
            field=models.ForeignKey(blank=True, help_text='Child this conversation is about (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_conversations', to='accounts.childprofile'),
        ),
    ]
