# Generated by Django 5.2.9 on 2026-02-23 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_userprofile_workshop_email_notifications'),
        ('courses', '0022_course_courses_cou_instruc_f1fbcf_idx'),
        ('lessons', '0014_alter_lessonassignment_unique_together_and_more'),
        ('messaging', '0004_alter_conversation_child_profile'),
        ('private_teaching', '0031_lessoncancellationrequest_initiated_by'),
        ('workshops', '0031_alter_workshopcartitem_child_profile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='lesson_assignment',
            field=models.ForeignKey(blank=True, help_text='Assignment this conversation is about', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='lessons.lessonassignment'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='private_lesson_assignment',
            field=models.ForeignKey(blank=True, help_text='Assignment this conversation is about (deprecated — use lesson_assignment)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='private_teaching.privatelessonassignment'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['lesson_assignment', '-updated_at'], name='messaging_c_lesson__cee56d_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('domain', 'private_teaching'), ('lesson_assignment__isnull', False)), fields=('lesson_assignment', 'participant_1', 'participant_2'), name='unique_lesson_assignment_conversation'),
        ),
    ]
