# Generated by Django 5.2.9 on 2026-02-23 13:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_userprofile_workshop_email_notifications'),
        ('courses', '0022_course_courses_cou_instruc_f1fbcf_idx'),
        ('lessons', '0014_alter_lessonassignment_unique_together_and_more'),
        ('messaging', '0005_conversation_lesson_assignment_and_more'),
        ('workshops', '0031_alter_workshopcartitem_child_profile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='conversation',
            name='unique_private_teaching_conversation',
        ),
        migrations.RemoveConstraint(
            model_name='conversation',
            name='unique_assignment_conversation',
        ),
        migrations.RemoveIndex(
            model_name='conversation',
            name='messaging_c_private_5d9f16_idx',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='private_lesson_assignment',
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('domain', 'private_teaching'), ('lesson_assignment__isnull', True)), fields=('participant_1', 'participant_2', 'child_profile'), name='unique_private_teaching_conversation'),
        ),
    ]
