# Generated by Django 5.2.9 on 2026-02-02 15:49

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0016_userprofile_workshop_email_notifications'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuralTrainingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('training', 'Training Mode'), ('drill', 'Drill Mode'), ('explore', 'Explore Mode')], default='training', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('questions_attempted', models.PositiveIntegerField(default=0)),
                ('questions_correct', models.PositiveIntegerField(default=0)),
                ('highest_streak', models.PositiveIntegerField(default=0)),
                ('current_level', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)])),
                ('child_profile', models.ForeignKey(blank=True, help_text='If session is for a child', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aural_training_sessions', to='accounts.childprofile')),
                ('student', models.ForeignKey(help_text='Student who completed the session', on_delete=django.db.models.deletion.CASCADE, related_name='aural_training_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aural Training Session',
                'verbose_name_plural': 'Aural Training Sessions',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['student', '-started_at'], name='aural_train_student_7908c0_idx'), models.Index(fields=['child_profile', '-started_at'], name='aural_train_child_p_440f2d_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentIntervalProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interval', models.CharField(choices=[('m2', 'Minor 2nd'), ('M2', 'Major 2nd'), ('m3', 'Minor 3rd'), ('M3', 'Major 3rd'), ('P4', 'Perfect 4th'), ('P5', 'Perfect 5th'), ('m6', 'Minor 6th'), ('M6', 'Major 6th'), ('m7', 'Minor 7th'), ('M7', 'Major 7th'), ('P8', 'Octave')], help_text='The interval being tracked', max_length=3)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('correct', models.PositiveIntegerField(default=0)),
                ('unlocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child_profile', models.ForeignKey(blank=True, help_text='If progress is for a child', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interval_progress', to='accounts.childprofile')),
                ('student', models.ForeignKey(help_text='Student tracking progress', on_delete=django.db.models.deletion.CASCADE, related_name='interval_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Interval Progress',
                'verbose_name_plural': 'Student Interval Progress',
                'indexes': [models.Index(fields=['student', 'interval'], name='aural_train_student_316366_idx'), models.Index(fields=['child_profile', 'interval'], name='aural_train_child_p_feaf90_idx')],
                'unique_together': {('student', 'child_profile', 'interval')},
            },
        ),
    ]
