# Generated by Django 5.2.9 on 2026-02-23 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_userprofile_workshop_email_notifications'),
        ('aural_training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auraltrainingsession',
            name='child_profile',
            field=models.ForeignKey(blank=True, help_text='If session is for a child', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aural_training_sessions', to='accounts.childprofile'),
        ),
        migrations.AlterField(
            model_name='studentintervalprogress',
            name='child_profile',
            field=models.ForeignKey(blank=True, help_text='If progress is for a child', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interval_progress', to='accounts.childprofile'),
        ),
    ]
