# Generated by Django 5.2.9 on 2026-05-24 10:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aural_training', '0002_alter_auraltrainingsession_child_profile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuralTestSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_shared', models.BooleanField(default=False, help_text="If true, all students on the platform can access this set; otherwise only this teacher's students.")),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aural_test_sets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aural Test Set',
                'verbose_name_plural': 'Aural Test Sets',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AuralTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('instructions', models.TextField(help_text='What the student should do after listening.')),
                ('audio_file', models.FileField(upload_to='aural_tests/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='aural_training.auraltestset')),
            ],
            options={
                'verbose_name': 'Aural Test',
                'verbose_name_plural': 'Aural Tests',
                'ordering': ['order', 'title'],
            },
        ),
    ]
