"""
Django settings for recordered project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECURITY FIX: Removed insecure default - SECRET_KEY must be set in environment
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# SECURITY FIX: Use environment variable instead of hardcoded value
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())

# CSRF trusted origins for Django 4.0+ (required for HTTPS)
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='', cast=Csv())

# Security settings for production
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'django.contrib.humanize',

    # Third party apps
    'rest_framework',
    'django_ckeditor_5',
    'django_filters',
    'django_recaptcha',  # django-recaptcha v4+
    'tailwind',
    'theme',

    # Local apps
    'apps.core',
    'apps.workshops',
    'apps.accounts',
    'apps.payments',
    'apps.private_teaching',
    'apps.expenses',
    'apps.courses',
    'apps.digital_products',
    'apps.audioplayer',
    'apps.messaging',
    'apps.support',
    'apps.help_center',
    'apps.admin_portal',
    'apps.teacher_applications',
    'lessons',
    'assignments',
    'apps.lesson_templates',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Add WhiteNoise for static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'apps.accounts.middleware.ProfileCompletionMiddleware',
]

ROOT_URLCONF = 'recordered.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.private_teaching.context_processors.cart_context',
                'apps.workshops.context_processors.unified_cart_context',
                'apps.messaging.context_processors.unread_messages',  # Unified messaging (includes course messages)
                'apps.accounts.context_processors.email_verification_status',
                'apps.admin_portal.context_processors.admin_metrics',  # Admin portal metrics
            ],
        },
    },
]

WSGI_APPLICATION = 'recordered.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Use PostgreSQL in production, SQLite in development
if config('DATABASE_URL', default=None):
    # Production database configuration
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('DB_NAME'),
            'USER': config('DB_USER'),
            'PASSWORD': config('DB_PASSWORD'),
            'HOST': config('DB_HOST', default='localhost'),
            'PORT': config('DB_PORT', default='5432'),
        }
    }
else:
    # Development database (SQLite)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise configuration for better static file serving
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# File upload size limits
# Set to 20MB to match nginx client_max_body_size (15MB) with some headroom
# This allows uploading multiple audio files for playalong pieces
DATA_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024  # 20MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024  # 20MB

# Email settings
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
    EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
    EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
    EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
    EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')

DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@workshopplatform.com')

# Stripe Payment Configuration
STRIPE_PUBLISHABLE_KEY = config('STRIPE_PUBLISHABLE_KEY', default='')
STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY', default='')
STRIPE_WEBHOOK_SECRET = config('STRIPE_WEBHOOK_SECRET', default='')

# Currency Configuration
CURRENCY_CODE = 'GBP'
CURRENCY_SYMBOL = '£'

# Platform Settings
PLATFORM_COMMISSION_PERCENTAGE = config('PLATFORM_COMMISSION_PERCENTAGE', default=10, cast=int)

# Business Logic Settings
# Workshop refund and cancellation policies
WORKSHOP_REFUND_DAYS = config('WORKSHOP_REFUND_DAYS', default=7, cast=int)  # Days before workshop for full refund
WAITLIST_PROMOTION_HOURS = config('WAITLIST_PROMOTION_HOURS', default=48, cast=int)  # Hours to accept waitlist promotion

# Private lesson policies
PRIVATE_LESSON_CANCELLATION_HOURS = config('PRIVATE_LESSON_CANCELLATION_HOURS', default=48, cast=int)  # Hours notice required
PRIVATE_LESSON_REFUND_REQUEST_DAYS = config('PRIVATE_LESSON_REFUND_REQUEST_DAYS', default=14, cast=int)  # Days after lesson to request refund

# Site configuration
SITE_ID = 1
SITE_NAME = 'Recorder-ed'
SITE_URL = config('SITE_URL', default='http://localhost:8000')

# Tailwind CSS Settings
TAILWIND_APP_NAME = 'theme'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Development settings
INTERNAL_IPS = [
    "127.0.0.1",
]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication settings
AUTHENTICATION_BACKENDS = [
    'apps.core.backends.EmailBackend',
    'django.contrib.auth.backends.ModelBackend',
]
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'  # Domain selector
LOGOUT_REDIRECT_URL = '/'

# CKEditor 5 Configuration
# Custom Color Palette for Table Styling
customColorPalette = [
    {'color': 'hsl(4, 90%, 58%)', 'label': 'Red'},
    {'color': 'hsl(340, 82%, 52%)', 'label': 'Pink'},
    {'color': 'hsl(291, 64%, 42%)', 'label': 'Purple'},
    {'color': 'hsl(262, 52%, 47%)', 'label': 'Deep Purple'},
    {'color': 'hsl(231, 48%, 48%)', 'label': 'Indigo'},
    {'color': 'hsl(207, 90%, 54%)', 'label': 'Blue'},
]

CKEDITOR_5_CONFIGS = {
    "default": {
        "toolbar": [
            "heading",
            "|",
            "bold",
            "italic",
            "underline",
            "strikethrough",
            "subscript",
            "superscript",
            "link",
            "bulletedList",
            "numberedList",
            "todoList",
            "blockQuote",
            "imageUpload",
            "imageInsert",
            "mediaEmbed",
            "htmlEmbed",
            "|",
            "fontColor",
            "fontBackgroundColor",
            "fontFamily",
            "fontSize",
            "alignment",
            "insertTable",
            "horizontalLine",
            "code",
            "codeBlock",
            "highlight",
            "removeFormat",
            "outdent",
            "indent",
            "sourceEditing"
        ],
        "fontFamily": {
            "options": [
                {
                    "title": "Default",
                    "model": "Arial, Helvetica, sans-serif",
                    "view": {
                        "name": "span",
                        "styles": {
                            "font-family": "Arial, Helvetica, sans-serif"
                        }
                    }
                },
                "Opus, sans-serif",
                "Times New Roman, Times, serif",
                "Courier New, Courier, monospace"
            ],
            "supportAllValues": True
        },
        "fontSize": {
            "options": [
                {"model": "8pt", "title": "8", "view": {"name": "span", "styles": {"font-size": "8pt"}}},
                {"model": "10pt", "title": "10", "view": {"name": "span", "styles": {"font-size": "10pt"}}},
                {"model": "12pt", "title": "12", "view": {"name": "span", "styles": {"font-size": "12pt"}}},
                {"model": "14pt", "title": "14", "view": {"name": "span", "styles": {"font-size": "14pt"}}},
                {"model": "16pt", "title": "16", "view": {"name": "span", "styles": {"font-size": "16pt"}}},
                {"model": "18pt", "title": "18", "view": {"name": "span", "styles": {"font-size": "18pt"}}},
                {"model": "24pt", "title": "24", "view": {"name": "span", "styles": {"font-size": "24pt"}}},
                {"model": "36pt", "title": "36", "view": {"name": "span", "styles": {"font-size": "36pt"}}}
            ],
            "supportAllValues": True
        },
        "mediaEmbed": {
            "previewsInData": True
        },
        "htmlSupport": {
            "allow": [
                {
                    "name": "hr",
                    "attributes": True,
                    "classes": True,
                    "styles": True
                },
                {
                    "name": "/.*/",
                    "attributes": True,
                    "classes": True,
                    "styles": True,
                    "children": True
                }
            ]
        },
        "image": {
            "toolbar": [
                "imageTextAlternative",
                "|",
                "imageStyle:full",
                "imageStyle:alignLeft",
                "imageStyle:alignRight",
                "imageStyle:alignCenter",
                "imageStyle:side",
                "|",
                "toggleImageCaption",
                "resizeImage",
                "|"
            ],
            "upload": {
                'types': ['jpeg', 'png', 'gif', 'svg+xml']
            },
            "styles": [
                "full",
                "side",
                "alignLeft",
                "alignRight",
                "alignCenter"
            ]
        },
        "table": {
            "contentToolbar": [
                "tableColumn",
                "tableRow",
                "mergeTableCells",
                "tableProperties",
                "tableCellProperties"
            ],
            "tableProperties": {
                "borderColors": customColorPalette,
                "backgroundColors": customColorPalette,
                "defaultProperties": {
                    "alignment": "left"
                }
            },
            "tableCellProperties": {
                "borderColors": customColorPalette,
                "backgroundColors": customColorPalette
            },
        },
        "heading": {
            "options": [
                {
                    "model": "paragraph",
                    "title": "Paragraph",
                    "class": "ck-heading_paragraph"
                },
                {
                    "model": "heading1",
                    "view": "h1",
                    "title": "Heading 1",
                    "class": "ck-heading_heading1"
                },
                {
                    "model": "heading2",
                    "view": "h2",
                    "title": "Heading 2",
                    "class": "ck-heading_heading2"
                },
                {
                    "model": "heading3",
                    "view": "h3",
                    "title": "Heading 3",
                    "class": "ck-heading_heading3"
                }
            ]
        },
        "list": {
            "properties": {
                "styles": True,
                "startIndex": True,
                "reversed": True
            }
        }
    },
    "comment": {
        "language": {"ui": "en", "content": "en"},
        "toolbar": [
            "heading",
            "|",
            "bold",
            "italic",
            "link",
            "bulletedList",
            "numberedList",
            "blockQuote"
        ]
    },
    "extends": {
        "language": "en",
        "blockToolbar": [
            "paragraph",
            "heading1",
            "heading2",
            "heading3",
            "|",
            "bulletedList",
            "numberedList",
            "|",
            "blockQuote"
        ],
        "toolbar": [
            "heading",
            "codeBlock",
            "|",
            "outdent",
            "indent",
            "|",
            "bold",
            "italic",
            "link",
            "underline",
            "strikethrough",
            "code",
            "subscript",
            "superscript",
            "highlight",
            "|",
            "bulletedList",
            "numberedList",
            "todoList",
            "|",
            "blockQuote",
            "insertImage",
            "|",
            "fontSize",
            "fontFamily",
            "fontColor",
            "fontBackgroundColor",
            "mediaEmbed",
            "removeFormat",
            "insertTable",
            "sourceEditing"
        ],
        "image": {
            "toolbar": [
                "imageTextAlternative",
                "|",
                "imageStyle:full",
                "imageStyle:alignLeft",
                "imageStyle:alignRight",
                "imageStyle:alignCenter",
                "imageStyle:side",
                "|",
                "toggleImageCaption",
                "|"
            ],
            "upload": {
                'types': ['jpeg', 'png', 'gif', 'svg+xml']
            },
            "styles": [
                "full",
                "side",
                "alignLeft",
                "alignRight",
                "alignCenter"
            ]
        },
        "table": {
            "contentToolbar": [
                "tableColumn",
                "tableRow",
                "mergeTableCells",
                "tableProperties",
                "tableCellProperties"
            ],
            "tableProperties": {
                "borderColors": customColorPalette,
                "backgroundColors": customColorPalette
            },
            "tableCellProperties": {
                "borderColors": customColorPalette,
                "backgroundColors": customColorPalette
            }
        },
        "heading": {
            "options": [
                {
                    "model": "paragraph",
                    "title": "Paragraph",
                    "class": "ck-heading_paragraph"
                },
                {
                    "model": "heading1",
                    "view": "h1",
                    "title": "Heading 1",
                    "class": "ck-heading_heading1"
                },
                {
                    "model": "heading2",
                    "view": "h2",
                    "title": "Heading 2",
                    "class": "ck-heading_heading2"
                },
                {
                    "model": "heading3",
                    "view": "h3",
                    "title": "Heading 3",
                    "class": "ck-heading_heading3"
                }
            ]
        },
        "list": {
            "properties": {
                "styles": True,
                "startIndex": True,
                "reversed": True
            }
        },
        "htmlSupport": {
            "allow": [
                {"name": "/.*/", "attributes": True, "classes": True, "styles": True}
            ]
        }
    }
}

# CKEditor 5 file upload settings
CKEDITOR_5_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"
# SECURITY FIX: Removed 'svg' (XSS risk) and restricted to safe image formats
CKEDITOR_5_UPLOAD_FILE_TYPES = ['jpeg', 'jpg', 'png', 'gif', 'bmp', 'webp']
CKEDITOR_5_UPLOAD_FILE_VIEW_NAME = "ck_editor_5_upload_file"
# SECURITY FIX: Changed from "any" to "authenticated" to prevent anonymous uploads
CKEDITOR_5_FILE_UPLOAD_PERMISSION = "authenticated"  # Options: "staff", "authenticated", "any"
# Upload to media/uploads/ (ensure this directory exists)
import os
CKEDITOR_5_UPLOADS_PATH = os.path.join(MEDIA_ROOT, "uploads/")

# ============================================
# Google reCAPTCHA v3 Configuration
# ============================================
RECAPTCHA_PUBLIC_KEY = config('RECAPTCHA_PUBLIC_KEY', default='')
RECAPTCHA_PRIVATE_KEY = config('RECAPTCHA_PRIVATE_KEY', default='')
# reCAPTCHA v3 specific settings
RECAPTCHA_REQUIRED_SCORE = 0.5  # Score threshold (0.0 - 1.0, higher = stricter)
RECAPTCHA_DOMAIN = 'www.google.com'  # Use 'www.recaptcha.net' in China
