# Generated by Django 5.2.7 on 2025-10-21 22:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopInterest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text="We'll notify you when sessions become available", max_length=254)),
                ('preferred_timing', models.CharField(choices=[('weekday_morning', 'Weekday Mornings'), ('weekday_afternoon', 'Weekday Afternoons'), ('weekday_evening', 'Weekday Evenings'), ('weekend_morning', 'Weekend Mornings'), ('weekend_afternoon', 'Weekend Afternoons'), ('weekend_evening', 'Weekend Evenings'), ('flexible', 'Flexible')], default='flexible', help_text='When would you prefer to attend?', max_length=20)),
                ('experience_level', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], help_text='Your current experience level with this topic', max_length=20)),
                ('special_requests', models.TextField(blank=True, help_text="Any specific topics you'd like covered or accessibility needs")),
                ('notify_immediately', models.BooleanField(default=True, help_text='Notify me as soon as sessions are scheduled')),
                ('notify_summary', models.BooleanField(default=False, help_text='Send me monthly summaries of new workshop opportunities')),
                ('is_active', models.BooleanField(default=True)),
                ('has_been_notified', models.BooleanField(default=False)),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_interests', to=settings.AUTH_USER_MODEL)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_requests', to='workshops.workshop')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workshop', 'is_active'], name='workshops_w_worksho_378351_idx'), models.Index(fields=['user', 'is_active'], name='workshops_w_user_id_7e6717_idx'), models.Index(fields=['has_been_notified', 'is_active'], name='workshops_w_has_bee_b978b5_idx')],
                'unique_together': {('workshop', 'user')},
            },
        ),
    ]
