# Generated by Django 5.2.7 on 2025-10-21 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_workshopinterest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='difficulty_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('mixed', 'Mixed Ability')], default='beginner', max_length=20),
        ),
        migrations.AlterField(
            model_name='workshopinterest',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('mixed', 'Mixed Ability')], help_text='Your current experience level with this topic', max_length=20),
        ),
        migrations.AlterField(
            model_name='workshopregistration',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('mixed', 'Mixed Ability')], max_length=20),
        ),
    ]
