# Generated by Django 5.2.7 on 2025-10-21 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0003_alter_workshop_difficulty_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='delivery_method',
            field=models.CharField(choices=[('online', 'Online'), ('in_person', 'In-Person'), ('hybrid', 'Hybrid (Online + In-Person)')], default='online', help_text='How will this workshop be delivered?', max_length=20),
        ),
        migrations.AddField(
            model_name='workshop',
            name='max_venue_capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum in-person participants (if different from online capacity)', null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='venue_address',
            field=models.TextField(blank=True, help_text='Street address of the venue'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='venue_city',
            field=models.CharField(blank=True, help_text='City where the venue is located', max_length=100),
        ),
        migrations.AddField(
            model_name='workshop',
            name='venue_map_link',
            field=models.URLField(blank=True, help_text='Link to Google Maps, Apple Maps, etc.'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='venue_name',
            field=models.CharField(blank=True, help_text='Name of the venue (required for in-person workshops)', max_length=200),
        ),
        migrations.AddField(
            model_name='workshop',
            name='venue_notes',
            field=models.TextField(blank=True, help_text='Additional venue info: parking, entrance, accessibility notes'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='venue_postcode',
            field=models.CharField(blank=True, help_text='Postal/ZIP code for the venue', max_length=20),
        ),
        migrations.AddField(
            model_name='workshopsession',
            name='session_delivery_override',
            field=models.CharField(blank=True, choices=[('online', 'Online'), ('in_person', 'In-Person'), ('hybrid', 'Hybrid (Online + In-Person)')], help_text='Override workshop delivery method for this specific session', max_length=20),
        ),
        migrations.AddField(
            model_name='workshopsession',
            name='session_venue_notes',
            field=models.TextField(blank=True, help_text='Session-specific venue information or changes'),
        ),
    ]
