# Generated by Django 5.2.7 on 2025-10-21 22:52

from django.db import migrations, models


def convert_duration_data(apps, schema_editor):
    """Convert existing estimated_duration to new flexible duration format"""
    Workshop = apps.get_model('workshops', 'Workshop')
    
    for workshop in Workshop.objects.all():
        duration_minutes = workshop.estimated_duration
        
        # Convert to most appropriate unit
        if duration_minutes >= 10080:  # 1 week or more
            workshop.duration_value = duration_minutes // 10080
            workshop.duration_unit = 'weeks'
        elif duration_minutes >= 1440:  # 1 day or more
            workshop.duration_value = duration_minutes // 1440
            workshop.duration_unit = 'days'
        elif duration_minutes >= 60:  # 1 hour or more
            workshop.duration_value = duration_minutes // 60
            workshop.duration_unit = 'hours'
        else:  # Less than 1 hour
            workshop.duration_value = duration_minutes
            workshop.duration_unit = 'minutes'
        
        workshop.save()


def reverse_convert_duration_data(apps, schema_editor):
    """Convert back to estimated_duration for rollback"""
    Workshop = apps.get_model('workshops', 'Workshop')
    
    multipliers = {
        'minutes': 1,
        'hours': 60,
        'days': 1440,
        'weeks': 10080
    }
    
    for workshop in Workshop.objects.all():
        workshop.estimated_duration = workshop.duration_value * multipliers.get(workshop.duration_unit, 1)
        workshop.save()


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0004_workshop_delivery_method_workshop_max_venue_capacity_and_more'),
    ]

    operations = [
        # Add new fields first
        migrations.AddField(
            model_name='workshop',
            name='duration_unit',
            field=models.CharField(choices=[('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks')], default='minutes', max_length=10),
        ),
        migrations.AddField(
            model_name='workshop',
            name='duration_value',
            field=models.PositiveIntegerField(default=60, help_text='Duration amount'),
        ),
        # Convert existing data
        migrations.RunPython(convert_duration_data, reverse_convert_duration_data),
        # Remove old field
        migrations.RemoveField(
            model_name='workshop',
            name='estimated_duration',
        ),
    ]
