# Generated by Django 5.2.7 on 2025-10-22 05:10

from django.db import migrations


def create_user_profiles(apps, schema_editor):
    """Create UserProfile instances for all existing users"""
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('workshops', 'UserProfile')
    
    for user in User.objects.all():
        profile, created = UserProfile.objects.get_or_create(
            user=user,
            defaults={
                'is_instructor': user.is_staff and not user.is_superuser,
                'bio': '',
                'website': ''
            }
        )
        if not created and user.is_staff and not user.is_superuser:
            # Update existing profiles for staff users who aren't superusers
            profile.is_instructor = True
            profile.save()


def reverse_user_profiles(apps, schema_editor):
    """Reverse the migration by deleting all UserProfile instances"""
    UserProfile = apps.get_model('workshops', 'UserProfile')
    UserProfile.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0006_userprofile'),
    ]

    operations = [
        migrations.RunPython(create_user_profiles, reverse_user_profiles),
    ]
