# Generated by Django 5.2.7 on 2025-10-22 09:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0007_auto_20251022_0510'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistPromotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('promoted_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(choices=[('capacity_increase', 'Session capacity increased'), ('manual_promotion', 'Manual promotion by instructor'), ('cancellation', 'Student cancellation opened spot')], max_length=30)),
                ('expires_at', models.DateTimeField(help_text='Deadline for student to confirm registration')),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='When student confirmed the promotion', null=True)),
                ('expired', models.BooleanField(default=False, help_text='Whether promotion expired unconfirmed')),
            ],
            options={
                'ordering': ['-promoted_at'],
            },
        ),
        migrations.AddField(
            model_name='workshopregistration',
            name='promoted_at',
            field=models.DateTimeField(blank=True, help_text='When moved from waitlist to registered', null=True),
        ),
        migrations.AddField(
            model_name='workshopregistration',
            name='promotion_expires_at',
            field=models.DateTimeField(blank=True, help_text='Deadline to confirm promotion', null=True),
        ),
        migrations.AddField(
            model_name='workshopregistration',
            name='promotion_notification_sent',
            field=models.BooleanField(default=False, help_text='Whether promotion notification was sent'),
        ),
        migrations.AddField(
            model_name='workshopregistration',
            name='waitlist_position',
            field=models.PositiveIntegerField(blank=True, help_text='Position in waitlist queue', null=True),
        ),
        migrations.AddIndex(
            model_name='workshopregistration',
            index=models.Index(fields=['session', 'waitlist_position'], name='workshops_w_session_f8b339_idx'),
        ),
        migrations.AddIndex(
            model_name='workshopregistration',
            index=models.Index(fields=['promotion_expires_at'], name='workshops_w_promoti_b5a5a9_idx'),
        ),
        migrations.AddField(
            model_name='waitlistpromotion',
            name='promoted_by',
            field=models.ForeignKey(blank=True, help_text='User who triggered promotion', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='waitlistpromotion',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='workshops.workshopregistration'),
        ),
        migrations.AddIndex(
            model_name='waitlistpromotion',
            index=models.Index(fields=['registration', 'promoted_at'], name='workshops_w_registr_00d1c7_idx'),
        ),
        migrations.AddIndex(
            model_name='waitlistpromotion',
            index=models.Index(fields=['expires_at', 'expired'], name='workshops_w_expires_1c3501_idx'),
        ),
    ]
