# Generated by Django 5.2.7 on 2025-10-22 09:46

from django.db import migrations


def set_waitlist_positions(apps, schema_editor):
    """Set waitlist positions for existing waitlisted registrations"""
    WorkshopRegistration = apps.get_model('workshops', 'WorkshopRegistration')
    WorkshopSession = apps.get_model('workshops', 'WorkshopSession')
    
    # Get all sessions
    sessions = WorkshopSession.objects.all()
    
    for session in sessions:
        # Get waitlisted registrations for this session ordered by registration date
        waitlisted = WorkshopRegistration.objects.filter(
            session=session,
            status='waitlisted'
        ).order_by('registration_date')
        
        # Assign positions starting from 1
        for index, registration in enumerate(waitlisted, start=1):
            registration.waitlist_position = index
            registration.save(update_fields=['waitlist_position'])


def reverse_waitlist_positions(apps, schema_editor):
    """Remove waitlist positions"""
    WorkshopRegistration = apps.get_model('workshops', 'WorkshopRegistration')
    WorkshopRegistration.objects.filter(
        status='waitlisted'
    ).update(waitlist_position=None)


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0008_add_waitlist_management'),
    ]

    operations = [
        migrations.RunPython(set_waitlist_positions, reverse_waitlist_positions),
    ]
