# Generated by Django 5.2.7 on 2025-10-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0009_set_waitlist_positions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopregistration',
            name='status',
            field=models.CharField(choices=[('registered', 'Registered'), ('waitlisted', 'Waitlisted'), ('promoted', 'Promoted (Awaiting Payment)'), ('attended', 'Attended'), ('no_show', 'No Show'), ('cancelled', 'Cancelled')], default='registered', max_length=20),
        ),
    ]
