# Generated by Django 5.2.7 on 2025-10-28 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_child_profile_model'),
        ('workshops', '0010_alter_workshopregistration_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workshopregistration',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='workshopregistration',
            name='child_profile',
            field=models.ForeignKey(blank=True, help_text='If registering a child, link to their child profile', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workshop_registrations', to='accounts.childprofile'),
        ),
        migrations.AlterField(
            model_name='workshopregistration',
            name='student',
            field=models.ForeignKey(help_text='For adults: the student. For children: the guardian/parent.', on_delete=django.db.models.deletion.CASCADE, related_name='workshop_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='workshopregistration',
            index=models.Index(fields=['child_profile', 'status'], name='workshops_w_child_p_46b652_idx'),
        ),
    ]
