# Generated by Django 5.2.7 on 2025-10-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0011_add_child_profile_to_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopregistration',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='When payment was completed', null=True),
        ),
        migrations.AddField(
            model_name='workshopregistration',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount paid for this registration', max_digits=10),
        ),
        migrations.AddField(
            model_name='workshopregistration',
            name='payment_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending Payment'), ('completed', 'Payment Completed'), ('failed', 'Payment Failed')], default='not_required', help_text='Payment status for paid workshops', max_length=20),
        ),
        migrations.AddField(
            model_name='workshopregistration',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, help_text='Stripe Checkout Session ID', max_length=255),
        ),
        migrations.AddField(
            model_name='workshopregistration',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, help_text='Stripe PaymentIntent ID', max_length=255),
        ),
        migrations.AlterField(
            model_name='workshopregistration',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('registered', 'Registered'), ('waitlisted', 'Waitlisted'), ('promoted', 'Promoted (Awaiting Payment)'), ('attended', 'Attended'), ('no_show', 'No Show'), ('cancelled', 'Cancelled')], default='registered', max_length=20),
        ),
    ]
