# Generated by Django 5.2.7 on 2025-11-04 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_accepting_new_private_students_and_more'),
        ('private_teaching', '0005_order_stripe_checkout_session_id_and_more'),
        ('workshops', '0012_workshopregistration_paid_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price at time of adding to cart', max_digits=10)),
                ('notes', models.TextField(blank=True, help_text='Optional notes for instructor')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(help_text='Cart this workshop session belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='workshop_items', to='private_teaching.cart')),
                ('child_profile', models.ForeignKey(blank=True, help_text='If registering a child, link to their child profile', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workshop_cart_items', to='accounts.childprofile')),
                ('session', models.ForeignKey(help_text='Workshop session to purchase', on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='workshops.workshopsession')),
            ],
            options={
                'verbose_name': 'Workshop Cart Item',
                'verbose_name_plural': 'Workshop Cart Items',
                'ordering': ['added_at'],
                'indexes': [models.Index(fields=['cart', 'added_at'], name='workshops_w_cart_id_4b5859_idx'), models.Index(fields=['session'], name='workshops_w_session_27a30c_idx')],
                'unique_together': {('cart', 'session')},
            },
        ),
    ]
