# Generated by Django 5.2.7 on 2025-11-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0013_workshopcartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopregistration',
            name='emergency_contact',
            field=models.CharField(blank=True, help_text='Emergency contact name and phone number (required for on-site workshops)', max_length=100),
        ),
    ]
