# Generated by Django 5.2.7 on 2025-11-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0014_workshopregistration_emergency_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopcartitem',
            name='email',
            field=models.EmailField(blank=True, help_text='Contact email for this registration', max_length=254),
        ),
        migrations.AddField(
            model_name='workshopcartitem',
            name='emergency_contact',
            field=models.CharField(blank=True, help_text='Emergency contact name and phone', max_length=100),
        ),
        migrations.AddField(
            model_name='workshopcartitem',
            name='expectations',
            field=models.TextField(blank=True, help_text='What the participant hopes to learn'),
        ),
        migrations.AddField(
            model_name='workshopcartitem',
            name='experience_level',
            field=models.CharField(blank=True, help_text='Experience level for this workshop', max_length=20),
        ),
        migrations.AddField(
            model_name='workshopcartitem',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=20),
        ),
        migrations.AddField(
            model_name='workshopcartitem',
            name='registration_completed',
            field=models.BooleanField(default=False, help_text='Whether the registration form has been filled out'),
        ),
        migrations.AddField(
            model_name='workshopcartitem',
            name='special_requirements',
            field=models.TextField(blank=True, help_text='Accessibility or other needs'),
        ),
    ]
