# Generated by Django 5.2.7 on 2025-11-12 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0015_workshopcartitem_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopregistration',
            name='expectations',
            field=models.TextField(blank=True, help_text='Which instruments do you play and intend to bring?'),
        ),
        migrations.AlterField(
            model_name='workshopregistration',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when payment was completed', null=True),
        ),
        migrations.AlterField(
            model_name='workshopregistration',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount paid or to be paid', max_digits=10),
        ),
        migrations.AlterField(
            model_name='workshopregistration',
            name='payment_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending Payment'), ('completed', 'Payment Completed'), ('failed', 'Payment Failed')], default='not_required', help_text='Current payment status', max_length=20),
        ),
        migrations.AlterField(
            model_name='workshopregistration',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, help_text='Stripe PaymentIntent ID for tracking', max_length=255),
        ),
    ]
