# Generated by Django 5.2.7 on 2025-11-12 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_accepting_new_private_students_and_more'),
        ('workshops', '0016_alter_workshopregistration_expectations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopregistration',
            name='child_profile',
            field=models.ForeignKey(blank=True, help_text='If for a child, link to their child profile', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.childprofile'),
        ),
    ]
