# Generated by Django 5.2.7 on 2025-11-21 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0017_alter_workshopregistration_child_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopTermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(help_text='Version number (e.g., 1, 2, 3)', unique=True)),
                ('content', models.TextField(help_text='Full Terms and Conditions text (supports Markdown)')),
                ('effective_date', models.DateTimeField(help_text='When these terms become effective')),
                ('is_current', models.BooleanField(default=False, help_text='Is this the current active version?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_terms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workshop Terms and Conditions',
                'verbose_name_plural': 'Workshop Terms and Conditions',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='TermsAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which terms were accepted', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent string')),
                ('registration', models.OneToOneField(blank=True, help_text='The workshop registration this acceptance is for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terms_acceptance', to='workshops.workshopregistration')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms_acceptances', to=settings.AUTH_USER_MODEL)),
                ('terms_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acceptances', to='workshops.workshoptermsandconditions')),
            ],
            options={
                'verbose_name': 'Terms Acceptance',
                'verbose_name_plural': 'Terms Acceptances',
                'ordering': ['-accepted_at'],
                'indexes': [models.Index(fields=['student', 'accepted_at'], name='workshops_t_student_a9c501_idx'), models.Index(fields=['registration'], name='workshops_t_registr_61467f_idx')],
            },
        ),
    ]
