# Generated by Django 5.2.7 on 2025-11-21 09:49

from django.db import migrations
from django.utils import timezone


INITIAL_TERMS_CONTENT = """# Workshop Terms and Conditions

**Last Updated: 21 November 2025**
**Version: 1.0**

## 1. Acceptance of Terms

By registering for any workshop on Recorder-ed, you agree to be bound by these Terms and Conditions. Please read them carefully before completing your registration.

## 2. Workshop Registration and Payment

2.1. Registration for a workshop is only confirmed upon receipt of full payment.

2.2. All prices are displayed in British Pounds (£) and include any applicable taxes.

2.3. Payment is processed securely through our payment provider, Stripe.

2.4. A platform fee is charged on all workshop registrations to cover administrative and operational costs.

## 3. Cancellation and Refund Policy

3.1. **Cancellations by Students:**
   - If you cancel your registration **7 days or more** before the workshop start date, you will receive a **full refund** of the workshop fee.
   - If you cancel your registration **less than 7 days** before the workshop start date, **no refund** will be provided.
   - The platform fee is non-refundable in all circumstances.

3.2. **Cancellations by Instructors:**
   - If an instructor cancels a workshop session, you will receive a full refund including the platform fee.
   - We will notify you as soon as possible of any cancellations and process refunds within 5-10 business days.

3.3. **Refund Processing:**
   - All eligible refunds will be processed to the original payment method within 5-10 business days.

## 4. Workshop Content and Quality

4.1. **No Guarantee of Content:** Workshop content, teaching methods, and difficulty levels are determined by individual instructors. Recorder-ed does not guarantee the suitability, quality, or appropriateness of workshop content for any particular participant.

4.2. **No Refunds for Content Dissatisfaction:** Refunds will not be provided if you find the workshop content too difficult, too easy, not as expected, or otherwise unsatisfactory. We encourage you to carefully review workshop descriptions, prerequisites, and instructor information before registering.

4.3. **Skill Level:** It is your responsibility to ensure that you or your child meets any stated prerequisites and that the workshop difficulty level is appropriate for your needs.

4.4. **Teaching Style:** Each instructor has their own teaching methodology. Differences in teaching style do not constitute grounds for a refund.

## 5. Workshop Attendance

5.1. **Online Workshops:** You are responsible for ensuring you have the necessary equipment, internet connection, and technical capability to participate in online workshops. Technical difficulties on your end do not constitute grounds for a refund.

5.2. **In-Person Workshops:** You are responsible for arranging your own transportation to and from in-person workshop venues.

5.3. **Late Arrival or Non-Attendance:** No refunds will be provided for late arrival, partial attendance, or non-attendance at workshops.

5.4. **Materials:** Unless explicitly stated in the workshop description, participants are responsible for providing their own instruments, materials, and equipment.

## 6. Participant Conduct

6.1. All participants are expected to behave respectfully toward instructors and other participants.

6.2. Recorder-ed and workshop instructors reserve the right to remove any participant who behaves disruptively or inappropriately. No refund will be provided in such cases.

6.3. For children's workshops, parents/guardians are responsible for their child's behavior during sessions.

## 7. Liability and Disclaimers

7.1. **Limitation of Liability:** Recorder-ed acts as a platform connecting students with independent workshop instructors. We are not responsible for the acts, omissions, or conduct of instructors or other participants.

7.2. **No Warranties:** Workshops are provided "as is" without any warranties, express or implied, including but not limited to warranties of educational quality, fitness for a particular purpose, or achievement of learning outcomes.

7.3. **Personal Injury:** Participation in workshops, particularly in-person sessions, is at your own risk. Recorder-ed is not liable for any personal injury, loss, or damage arising from workshop participation.

7.4. **Maximum Liability:** In no event shall Recorder-ed's total liability exceed the amount you paid for the workshop registration.

## 8. Data Protection and Privacy

8.1. We collect and process personal data in accordance with UK GDPR and our Privacy Policy.

8.2. By registering for a workshop, you consent to us sharing your contact information with the workshop instructor for the purpose of delivering the workshop.

8.3. Instructors may not use your personal data for any purpose other than delivering the workshop without your explicit consent.

8.4. **Children's Data:** For participants under 18, we collect data only with parental/guardian consent and in accordance with applicable child protection laws.

## 9. Intellectual Property

9.1. Workshop materials, handouts, and recordings provided by instructors are for your personal use only and may not be shared, reproduced, or distributed without permission.

9.2. Instructors retain all intellectual property rights to their workshop content.

## 10. Recording and Photography

10.1. Some workshops may be recorded for educational purposes. You will be notified if recording will take place.

10.2. By participating, you consent to being included in workshop recordings unless you explicitly opt out.

10.3. Participants may not record workshops without the instructor's explicit permission.

## 11. Changes to Workshops

11.1. Instructors reserve the right to make minor changes to workshop content, format, or schedule. We will notify you of any significant changes.

11.2. If substantial changes are made that materially affect the workshop, you may be entitled to a refund at our discretion.

## 12. Age Requirements

12.1. For adult workshops, participants must be 18 years or older unless otherwise stated.

12.2. For children's workshops, registrations must be made by a parent or legal guardian.

12.3. Age restrictions stated in workshop descriptions must be adhered to.

## 13. Platform Changes

13.1. Recorder-ed reserves the right to modify these Terms and Conditions at any time.

13.2. Changes will be effective immediately upon posting to the website.

13.3. Your continued use of the platform after changes constitutes acceptance of the modified terms.

13.4. For registered workshops, the terms in effect at the time of your registration will apply.

## 14. Dispute Resolution

14.1. We encourage you to contact us directly to resolve any disputes or concerns.

14.2. These terms are governed by the laws of England and Wales.

14.3. Any disputes shall be subject to the exclusive jurisdiction of the courts of England and Wales.

## 15. Contact Information

If you have any questions about these Terms and Conditions, please contact us at:
- Email: support@recorder-ed.com
- Website: www.recorder-ed.com

## 16. Severability

If any provision of these Terms and Conditions is found to be unenforceable or invalid, that provision shall be limited or eliminated to the minimum extent necessary, and the remaining provisions shall remain in full force and effect.

---

**By checking the acceptance box and proceeding with payment, you acknowledge that you have read, understood, and agree to be bound by these Terms and Conditions.**
"""


def seed_initial_terms(apps, schema_editor):
    """Create initial version of Terms and Conditions"""
    WorkshopTermsAndConditions = apps.get_model('workshops', 'WorkshopTermsAndConditions')
    User = apps.get_model('auth', 'User')

    # Get first superuser or create a system user
    admin_user = User.objects.filter(is_superuser=True).first()

    # Create initial terms
    WorkshopTermsAndConditions.objects.create(
        version=1,
        content=INITIAL_TERMS_CONTENT,
        effective_date=timezone.now(),
        is_current=True,
        created_by=admin_user
    )


def reverse_seed(apps, schema_editor):
    """Remove seeded terms if migration is reversed"""
    WorkshopTermsAndConditions = apps.get_model('workshops', 'WorkshopTermsAndConditions')
    WorkshopTermsAndConditions.objects.filter(version=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0018_workshoptermsandconditions_termsacceptance'),
    ]

    operations = [
        migrations.RunPython(seed_initial_terms, reverse_seed),
    ]
