# Generated by Django 5.2.7 on 2025-11-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0019_seed_initial_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='is_series',
            field=models.BooleanField(default=False, help_text='Is this workshop a multi-session series that should be purchased together?'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='require_full_series_registration',
            field=models.BooleanField(default=False, help_text='If checked, students must register for ALL sessions together (cannot register for individual sessions)'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='series_description',
            field=models.TextField(blank=True, help_text='Describe the series structure and what each session covers'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='series_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discounted price for purchasing all sessions in the series (leave blank if no discount)', max_digits=10, null=True),
        ),
    ]
