# Generated by Django 5.2.7 on 2025-11-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0020_add_workshop_series_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopsession',
            name='session_title',
            field=models.CharField(blank=True, help_text="Optional title for this session (e.g., 'Session 1: Basic Technique', 'Articulation Part 1')", max_length=200),
        ),
    ]
