# Generated by Django 5.2.7 on 2025-12-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0022_add_series_registration_grouping'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='workshopregistration',
            name='workshops_w_series__idx',
        ),
        migrations.AlterField(
            model_name='waitlistpromotion',
            name='reason',
            field=models.CharField(choices=[('capacity_increase', 'Session capacity increased'), ('manual_promotion', 'Manual promotion by instructor'), ('cancellation', 'Student cancellation opened place')], max_length=30),
        ),
    ]
