# Generated by Django 5.2.7 on 2025-12-11 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0023_remove_workshopregistration_workshops_w_series__idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopmaterial',
            name='file',
            field=models.FileField(blank=True, help_text='Allowed formats: PDF, Word, Text, Images. Max size: 10MB', null=True, upload_to='workshops/materials/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'txt', 'png', 'jpg', 'jpeg'])]),
        ),
    ]
