# Generated by Django 5.2.7 on 2025-12-17 19:30

import apps.workshops.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0025_remove_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Upload an image (will be automatically optimized to 800x400px). Max size: 5MB. Recommended: 2:1 aspect ratio.', null=True, upload_to='workshops/images/', validators=[apps.workshops.models.validate_workshop_image_size]),
        ),
    ]
