# Generated by Django 5.2.9 on 2026-02-11 12:43

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0029_session_email_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopTestimonial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(help_text="Public attribution, e.g. 'Sarah T.'", max_length=100)),
                ('quote', models.TextField()),
                ('rating', models.PositiveIntegerField(help_text='Internal reference only — not displayed publicly', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_published', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('registration', models.OneToOneField(blank=True, help_text='Linked feedback entry, if created from a student submission', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshops.workshopregistration')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='workshops.workshop')),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
                'indexes': [models.Index(fields=['workshop', 'is_published'], name='workshops_w_worksho_8fe32b_idx')],
            },
        ),
    ]
