# Generated by Django 4.2.28 on 2026-02-23 22:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0016_userprofile_workshop_email_notifications'),
        ('workshops', '0032_update_workshopcartitem_cart_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalWorkshopRegistration',
            fields=[
                ('payment_status', models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending Payment'), ('completed', 'Payment Completed'), ('failed', 'Payment Failed')], default='not_required', help_text='Current payment status', max_length=20)),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount paid or to be paid', max_digits=10)),
                ('stripe_payment_intent_id', models.CharField(blank=True, help_text='Stripe PaymentIntent ID for tracking', max_length=255)),
                ('stripe_checkout_session_id', models.CharField(blank=True, help_text='Stripe Checkout Session ID', max_length=255)),
                ('paid_at', models.DateTimeField(blank=True, help_text='Timestamp when payment was completed', null=True)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('registered', 'Registered'), ('waitlisted', 'Waitlisted'), ('promoted', 'Promoted (Awaiting Payment)'), ('attended', 'Attended'), ('no_show', 'No Show'), ('cancelled', 'Cancelled')], default='registered', max_length=20)),
                ('registration_date', models.DateTimeField(blank=True, editable=False)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('emergency_contact', models.CharField(blank=True, help_text='Emergency contact name and phone number (required for on-site workshops)', max_length=100)),
                ('experience_level', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('mixed', 'Mixed Ability')], max_length=20)),
                ('expectations', models.TextField(blank=True, help_text='Which instruments do you play and intend to bring?')),
                ('special_requirements', models.TextField(blank=True, help_text='Accessibility or other needs')),
                ('attended', models.BooleanField(default=False)),
                ('rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('feedback', models.TextField(blank=True)),
                ('waitlist_position', models.PositiveIntegerField(blank=True, help_text='Position in waitlist queue', null=True)),
                ('promoted_at', models.DateTimeField(blank=True, help_text='When moved from waitlist to registered', null=True)),
                ('promotion_expires_at', models.DateTimeField(blank=True, help_text='Deadline to confirm promotion', null=True)),
                ('promotion_notification_sent', models.BooleanField(default=False, help_text='Whether promotion notification was sent')),
                ('series_registration_id', models.UUIDField(blank=True, help_text='Links registrations that were purchased together as a mandatory series. All registrations with the same series_registration_id should be cancelled together.', null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('child_profile', models.ForeignKey(blank=True, db_constraint=False, help_text='If for a child, link to their child profile', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.childprofile')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workshops.workshopsession')),
                ('student', models.ForeignKey(blank=True, db_constraint=False, help_text='For adults: the student. For children: the guardian/parent.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical workshop registration',
                'verbose_name_plural': 'historical workshop registrations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
