# Generated by Django 5.2.9 on 2026-04-03 10:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_userprofile_lesson_reminder_notifications'),
        ('workshops', '0033_historicalworkshopregistration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopCompetition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='competition', to='workshops.workshopsession')),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopCompetitionAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='workshops.workshopcompetition')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkshopCompetitionEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('child_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competition_entries', to='accounts.childprofile')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='workshops.workshopcompetition')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_entries', to=settings.AUTH_USER_MODEL)),
                ('selected_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='workshops.workshopcompetitionanswer')),
            ],
            options={
                'unique_together': {('competition', 'participant')},
            },
        ),
        migrations.AddField(
            model_name='workshopcompetition',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_competition', to='workshops.workshopcompetitionentry'),
        ),
    ]
