# Generated by Django 5.2.9 on 2026-04-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0034_workshopcompetition_workshopcompetitionanswer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopcompetition',
            name='draw_datetime',
            field=models.DateTimeField(blank=True, help_text='Earliest date and time the winner draw can be performed', null=True),
        ),
    ]
