# Generated by Django 5.2.9 on 2026-08-19 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0035_add_draw_datetime_to_competition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workshopinterest',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='workshopinterest',
            name='country',
            field=models.CharField(choices=[('GB', 'United Kingdom'), ('US', 'United States'), ('CA', 'Canada'), ('AU', 'Australia'), ('NZ', 'New Zealand'), ('IE', 'Ireland'), ('NL', 'Netherlands'), ('DE', 'Germany'), ('ZA', 'South Africa'), ('OTHER', 'Other')], default='GB', help_text="Where you'll be joining from", max_length=10),
        ),
        migrations.AddField(
            model_name='workshopinterest',
            name='referral_source',
            field=models.CharField(blank=True, help_text='Campaign/partner tag captured from a ?src= link, e.g. an overseas newsletter', max_length=100),
        ),
        migrations.AlterField(
            model_name='workshopinterest',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Blank for anonymous interest requests (e.g. from overseas newsletter links)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workshop_interests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='workshopinterest',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('workshop', 'user'), name='unique_workshop_user_interest'),
        ),
        migrations.AddConstraint(
            model_name='workshopinterest',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('workshop', 'email'), name='unique_workshop_anon_email_interest'),
        ),
    ]
