# Generated by Django 5.2.9 on 2026-09-19 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0036_alter_workshopinterest_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshops.workshopcategory'),
        ),
    ]
