# Generated by Django 5.2.9 on 2026-05-12 07:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0017_userprofile_lesson_reminder_notifications'),
        ('lessons', '0017_standaloneDocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SightReadingAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_unlocked', models.BooleanField(default=False)),
                ('needs_repeat', models.BooleanField(default=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('child_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sight_reading_assignments', to='accounts.childprofile')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sight_reading_assignments', to='lessons.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sight_reading_assignments_received', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sight_reading_assignments_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='SightReadingExample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('grade_level', models.CharField(blank=True, help_text="e.g. '1', 'Beginner'", max_length=50)),
                ('image', models.ImageField(upload_to='sight_reading/examples/')),
                ('teacher_notes', models.TextField(blank=True, help_text='Private notes about this example (teacher only)')),
                ('is_public', models.BooleanField(default=False, help_text='Visible to all teachers in the library')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sight_reading_examples', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SightReadingResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
                ('result', models.CharField(blank=True, choices=[('correct', 'Correct'), ('incorrect', 'Incorrect')], max_length=20, null=True)),
                ('teacher_note', models.TextField(blank=True)),
                ('played_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='sight_reading.sightreadingassignment')),
                ('example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='sight_reading.sightreadingexample')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SightReadingSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('grade_level', models.CharField(blank=True, max_length=50)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sight_reading_sets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='sightreadingassignment',
            name='sight_reading_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='sight_reading.sightreadingset'),
        ),
        migrations.CreateModel(
            name='SightReadingSetItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_items', to='sight_reading.sightreadingexample')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sight_reading.sightreadingset')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='sightreadingset',
            name='examples',
            field=models.ManyToManyField(related_name='sets', through='sight_reading.SightReadingSetItem', to='sight_reading.sightreadingexample'),
        ),
        migrations.AddIndex(
            model_name='sightreadingexample',
            index=models.Index(fields=['created_by', 'grade_level'], name='sight_readi_created_7fcb0f_idx'),
        ),
        migrations.AddIndex(
            model_name='sightreadingexample',
            index=models.Index(fields=['is_public', 'grade_level'], name='sight_readi_is_publ_c87fd4_idx'),
        ),
        migrations.AddIndex(
            model_name='sightreadingresult',
            index=models.Index(fields=['assignment', 'order'], name='sight_readi_assignm_4521ba_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sightreadingresult',
            unique_together={('assignment', 'example')},
        ),
        migrations.AddIndex(
            model_name='sightreadingassignment',
            index=models.Index(fields=['teacher', 'needs_repeat'], name='sight_readi_teacher_b5e664_idx'),
        ),
        migrations.AddIndex(
            model_name='sightreadingassignment',
            index=models.Index(fields=['student', 'is_unlocked'], name='sight_readi_student_a8cd8e_idx'),
        ),
        migrations.AddIndex(
            model_name='sightreadingsetitem',
            index=models.Index(fields=['set', 'order'], name='sight_readi_set_id_0528c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sightreadingsetitem',
            unique_together={('set', 'example')},
        ),
    ]
