# Generated by Django 5.2.9 on 2025-12-30 09:27

import django.db.models.deletion
import django_ckeditor_5.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('private_teaching', '0023_add_max_recurring_lessons'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lesson Template Tag',
                'verbose_name_plural': 'Lesson Template Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LessonContentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text="Template title (e.g., 'ABRSM Grade 1 - Lesson 1: Introduction to Notation')", max_length=200)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(help_text='Lesson content with rich text formatting')),
                ('syllabus', models.CharField(blank=True, choices=[('abrsm', 'ABRSM'), ('trinity', 'Trinity College'), ('rcm', 'RCM'), ('custom', 'Custom')], help_text='Syllabus/examination board', max_length=50)),
                ('grade_level', models.CharField(blank=True, help_text="Grade level (e.g., '1', '2', 'Beginner', 'Intermediate')", max_length=10)),
                ('lesson_number', models.IntegerField(blank=True, help_text='Position in course sequence (1-12, etc.)', null=True)),
                ('is_public', models.BooleanField(default=False, help_text='If checked, other teachers can browse and use this template')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('use_count', models.IntegerField(default=0, help_text='Number of times this template has been used')),
                ('created_by', models.ForeignKey(help_text='Teacher who created this template', on_delete=django.db.models.deletion.CASCADE, related_name='created_lesson_templates', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, help_text='Subject this template is for', null=True, on_delete=django.db.models.deletion.SET_NULL, to='private_teaching.subject')),
                ('tags', models.ManyToManyField(blank=True, help_text='Tags for categorization (e.g., Scales, Rhythm, Theory)', related_name='templates', to='lesson_templates.tag')),
            ],
            options={
                'verbose_name': 'Lesson Content Template',
                'verbose_name_plural': 'Lesson Content Templates',
                'ordering': ['syllabus', 'grade_level', 'lesson_number', 'title'],
                'indexes': [models.Index(fields=['created_by', '-created_at'], name='lesson_temp_created_1eb770_idx'), models.Index(fields=['syllabus', 'grade_level', 'lesson_number'], name='lesson_temp_syllabu_9096cd_idx'), models.Index(fields=['is_public'], name='lesson_temp_is_publ_ac765e_idx')],
            },
        ),
    ]
