# Generated by Django 5.2.9 on 2026-01-20 07:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_templates', '0001_initial'),
        ('private_teaching', '0028_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessoncontenttemplate',
            options={'ordering': ['category', 'lesson_number', 'syllabus', 'grade_level', 'title'], 'verbose_name': 'Lesson Content Template', 'verbose_name_plural': 'Lesson Content Templates'},
        ),
        migrations.AlterField(
            model_name='lessoncontenttemplate',
            name='lesson_number',
            field=models.IntegerField(blank=True, help_text='Position in course sequence within this category (1, 2, 3, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='lessoncontenttemplate',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='Subject this template is for (can also be set on category)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='private_teaching.subject'),
        ),
        migrations.AlterField(
            model_name='lessoncontenttemplate',
            name='syllabus',
            field=models.CharField(blank=True, choices=[('abrsm', 'ABRSM'), ('trinity', 'Trinity College'), ('rcm', 'RCM'), ('mtb', 'Music Teachers Board'), ('custom', 'Custom')], help_text='Syllabus/examination board (can also be set on category)', max_length=50),
        ),
        migrations.CreateModel(
            name='TemplateCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Category name (e.g., 'Rhythm Fundamentals', 'ABRSM Grade 1 Theory')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description of what this category covers')),
                ('syllabus', models.CharField(blank=True, choices=[('abrsm', 'ABRSM'), ('trinity', 'Trinity College'), ('rcm', 'RCM'), ('mtb', 'Music Teachers Board'), ('custom', 'Custom')], help_text='Optional: Examination board or syllabus', max_length=50)),
                ('grade_level', models.CharField(blank=True, help_text="Optional: Grade level (e.g., '1', '2', 'Beginner')", max_length=10)),
                ('color', models.CharField(choices=[('#6366f1', 'Indigo'), ('#8b5cf6', 'Purple'), ('#ec4899', 'Pink'), ('#ef4444', 'Red'), ('#f97316', 'Orange'), ('#eab308', 'Yellow'), ('#22c55e', 'Green'), ('#14b8a6', 'Teal'), ('#3b82f6', 'Blue'), ('#64748b', 'Slate')], default='#6366f1', help_text='Color for category badge in UI', max_length=7)),
                ('display_order', models.IntegerField(default=0, help_text='Order in which categories are displayed (lower numbers first)')),
                ('is_public', models.BooleanField(default=False, help_text='If checked, other teachers can see this category (templates have independent visibility)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Teacher who created this category', on_delete=django.db.models.deletion.CASCADE, related_name='template_categories', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, help_text='Optional: Link to a specific subject/instrument', null=True, on_delete=django.db.models.deletion.SET_NULL, to='private_teaching.subject')),
            ],
            options={
                'verbose_name': 'Template Category',
                'verbose_name_plural': 'Template Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='lessoncontenttemplate',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category/series this template belongs to (lesson numbers are scoped within category)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='lesson_templates.templatecategory'),
        ),
        migrations.AddIndex(
            model_name='lessoncontenttemplate',
            index=models.Index(fields=['category', 'lesson_number'], name='lesson_temp_categor_04c2f9_idx'),
        ),
        migrations.AddIndex(
            model_name='templatecategory',
            index=models.Index(fields=['created_by', 'display_order'], name='lesson_temp_created_17ebb6_idx'),
        ),
        migrations.AddIndex(
            model_name='templatecategory',
            index=models.Index(fields=['is_public'], name='lesson_temp_is_publ_fd06c3_idx'),
        ),
    ]
