# Generated by Django 5.2.9 on 2026-01-20 11:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_templates', '0002_alter_lessoncontenttemplate_options_and_more'),
        ('private_teaching', '0028_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='templatecategory',
            constraint=models.UniqueConstraint(fields=('name', 'created_by'), name='unique_category_name_per_user'),
        ),
    ]
