# Generated by Django 5.2.7 on 2025-12-12 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of applicant', max_length=200)),
                ('email', models.EmailField(help_text='Contact email address', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Optional phone number', max_length=20)),
                ('teaching_biography', models.TextField(help_text='Teaching experience, musical background, and approach')),
                ('qualifications', models.TextField(help_text='Relevant qualifications, certifications, or professional memberships')),
                ('subjects', models.CharField(help_text='Instruments or subjects they teach (comma-separated)', max_length=500)),
                ('dbs_check_status', models.CharField(choices=[('yes', 'Yes - I have a current DBS check'), ('in_progress', 'In progress - I am obtaining one'), ('no', 'No - I do not have one'), ('equivalent', 'I have an equivalent background check')], help_text='DBS/background check status', max_length=20)),
                ('teaching_formats', models.CharField(help_text='Preferred teaching formats (comma-separated)', max_length=100)),
                ('availability', models.TextField(help_text='General availability for teaching')),
                ('terms_agreed', models.BooleanField(default=False, help_text='Applicant agreed to platform terms')),
                ('terms_agreed_at', models.DateTimeField(blank=True, help_text='When terms were agreed to', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('on_hold', 'On Hold')], db_index=True, default='pending', help_text='Current status of the application', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the application was reviewed', null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes from admin review (not visible to applicant)')),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (sent to applicant if rejected)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Staff member who reviewed this application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='Linked user account if applicant was logged in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher Application',
                'verbose_name_plural': 'Teacher Applications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='teacher_app_created_331b9d_idx'), models.Index(fields=['status', '-created_at'], name='teacher_app_status_253471_idx')],
            },
        ),
    ]
