# Generated by Django 5.2.7 on 2025-12-13 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_1_profile_complete', models.BooleanField(default=False, help_text='Step 1: Complete profile information')),
                ('step_1_completed_at', models.DateTimeField(blank=True, null=True)),
                ('step_2_qualifications_added', models.BooleanField(default=False, help_text='Step 2: Add teaching qualifications and experience')),
                ('step_2_completed_at', models.DateTimeField(blank=True, null=True)),
                ('step_3_availability_set', models.BooleanField(default=False, help_text='Step 3: Set teaching availability and preferences')),
                ('step_3_completed_at', models.DateTimeField(blank=True, null=True)),
                ('step_4_payment_setup', models.BooleanField(default=False, help_text='Step 4: Set up payment information for receiving fees')),
                ('step_4_completed_at', models.DateTimeField(blank=True, null=True)),
                ('step_5_first_listing_created', models.BooleanField(default=False, help_text='Step 5: Create first workshop or private teaching listing')),
                ('step_5_completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False, help_text='All onboarding steps completed')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When onboarding was fully completed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(blank=True, help_text='Original teacher application (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding', to='teacher_applications.teacherapplication')),
                ('user', models.OneToOneField(help_text='Teacher user account', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_onboarding', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher Onboarding',
                'verbose_name_plural': 'Teacher Onboardings',
                'ordering': ['-created_at'],
            },
        ),
    ]
