# Generated by Django 5.2.7 on 2025-11-12 13:29

from django.db import migrations


def update_site_domain(apps, schema_editor):
    """Update the default Site domain from example.com to recorder-ed.com"""
    Site = apps.get_model('sites', 'Site')
    try:
        site = Site.objects.get(id=1)
        site.domain = 'recorder-ed.com'
        site.name = 'RECORDERED'
        site.save()
        print(f"Updated Site domain to: {site.domain}")
    except Site.DoesNotExist:
        # Create the site if it doesn't exist
        Site.objects.create(id=1, domain='recorder-ed.com', name='RECORDERED')
        print("Created Site with domain: recorder-ed.com")


def reverse_site_domain(apps, schema_editor):
    """Reverse the site domain update"""
    Site = apps.get_model('sites', 'Site')
    try:
        site = Site.objects.get(id=1)
        site.domain = 'example.com'
        site.name = 'example.com'
        site.save()
    except Site.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.RunPython(update_site_domain, reverse_site_domain),
    ]
