# Generated by Django 5.2.9 on 2026-04-03 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0002_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=50)),
                ('reminder_type', models.CharField(choices=[('workshop_student', 'Workshop - Student'), ('workshop_instructor', 'Workshop - Instructor'), ('lesson_student', 'Lesson - Student'), ('lesson_teacher', 'Lesson - Teacher')], max_length=30)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('lead_hours', models.PositiveIntegerField(help_text='Configured lead time (hours) at the time this reminder was sent')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Reminder Log',
                'verbose_name_plural': 'Reminder Logs',
                'db_table': 'core_reminder_log',
                'indexes': [models.Index(fields=['content_type', 'object_id', 'reminder_type'], name='core_reminderlog_lookup_idx')],
            },
        ),
    ]
