# Generated by Django 5.2.7 on 2025-10-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemessage',
            name='category',
            field=models.CharField(choices=[('content_question', '📚 Content Question'), ('technical_issue', '🐛 Technical Issue'), ('content_error', '✏️ Content Error/Typo'), ('suggestion', '💡 Suggestion'), ('other', '❓ Other')], default='other', help_text='Type of message', max_length=20),
        ),
    ]
