# Generated by Django 5.2.7 on 2025-10-28 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_child_profile_model'),
        ('courses', '0002_coursemessage_category'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseenrollment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='child_profile',
            field=models.ForeignKey(blank=True, help_text='If enrolling a child, link to their child profile', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to='accounts.childprofile'),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='student',
            field=models.ForeignKey(help_text='For adults: the student. For children: the guardian/parent.', on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['child_profile', 'is_active'], name='courses_cou_child_p_a8e6a2_idx'),
        ),
    ]
