# Generated by Django 5.2.7 on 2025-10-30 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_add_child_profile_to_enrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseenrollment',
            name='order',
        ),
    ]
