# Generated by Django 5.2.7 on 2025-10-31 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_courseenrollment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='When payment was completed', null=True),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount paid for this enrollment', max_digits=10),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='payment_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending Payment'), ('completed', 'Payment Completed'), ('failed', 'Payment Failed')], default='not_required', help_text='Payment status for paid courses', max_length=20),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, help_text='Stripe Checkout Session ID', max_length=255),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, help_text='Stripe PaymentIntent ID', max_length=255),
        ),
    ]
