# Generated by Django 5.2.7 on 2025-11-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_courseenrollment_paid_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='expected_launch_date',
            field=models.DateField(blank=True, help_text='Optional: When do you plan to launch? Auto-hides 30 days after this date if still draft', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='show_as_coming_soon',
            field=models.BooleanField(default=False, help_text="Show this draft course publicly with 'Coming Soon' banner"),
        ),
    ]
