# Generated by Django 5.2.7 on 2025-11-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioplayer', '0001_initial'),
        ('courses', '0006_course_expected_launch_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='pieces',
            field=models.ManyToManyField(blank=True, help_text='Interactive playalong pieces for this lesson', related_name='lessons', through='audioplayer.LessonPiece', to='audioplayer.piece'),
        ),
    ]
