# Generated by Django 5.2.7 on 2025-11-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_courseenrollment_child_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemessage',
            name='is_read',
            field=models.BooleanField(default=False, help_text='Whether this message has been read'),
        ),
    ]
