# Generated by Django 5.2.7 on 2025-11-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_coursemessage_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonattachment',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
