# Generated by Django 5.2.7 on 2025-11-21 14:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_courseenrollment_student_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTermsAndConditions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(help_text='Version number (1, 2, 3...)', unique=True)),
                ('content', models.TextField(help_text='Full T&Cs content in Markdown format')),
                ('is_current', models.BooleanField(default=False, help_text='Is this the current active version? Only one version can be current at a time.')),
                ('effective_date', models.DateField(default=django.utils.timezone.now, help_text='Date these terms became/will become effective')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course Terms and Conditions',
                'verbose_name_plural': 'Course Terms and Conditions',
                'ordering': ['-version'],
            },
        ),
        migrations.AlterField(
            model_name='lessonattachment',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='CourseTermsAcceptance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('enrollment', models.OneToOneField(help_text='The course enrollment this acceptance is for', on_delete=django.db.models.deletion.CASCADE, related_name='terms_acceptance', to='courses.courseenrollment')),
                ('terms_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acceptances', to='courses.coursetermsandconditions')),
            ],
            options={
                'verbose_name': 'Course Terms Acceptance',
                'verbose_name_plural': 'Course Terms Acceptances',
            },
        ),
        migrations.CreateModel(
            name='CourseCancellationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(help_text="Student's reason for cancellation")),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed (Refund Processed)')], default='pending', max_length=20)),
                ('is_eligible_for_refund', models.BooleanField(default=False, help_text='Is this cancellation within the 7-day trial period?')),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Full course price (no platform fee)', max_digits=10, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes/response')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('refund_processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_requests', to='courses.courseenrollment')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_course_cancellations', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_cancellation_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'status'], name='courses_cou_student_2b07ab_idx'), models.Index(fields=['enrollment', 'status'], name='courses_cou_enrollm_af93e3_idx'), models.Index(fields=['status', 'created_at'], name='courses_cou_status_2244a2_idx')],
            },
        ),
    ]
