# Generated by Django 5.2.7 on 2025-11-21 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_merge_20251121_1500'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecancellationrequest',
            name='is_eligible_for_refund',
            field=models.BooleanField(default=False, help_text='Is this cancellation eligible for refund?'),
        ),
        migrations.AlterField(
            model_name='coursecancellationrequest',
            name='refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount to be refunded', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='coursecancellationrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Admin who reviewed this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coursecancellationrequest',
            name='student',
            field=models.ForeignKey(help_text='Student requesting cancellation', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lessonattachment',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
