# Generated by Django 5.2.7 on 2025-11-21 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_lessonattachment_created_at'),
        ('courses', '0016_alter_coursecancellationrequest_is_eligible_for_refund_and_more'),
    ]

    operations = [
    ]
