# Generated by Django 5.2.7 on 2025-11-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_merge_20251121_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonattachment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lessonattachment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lessonattachment',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order'),
        ),
        migrations.AlterField(
            model_name='lessonattachment',
            name='title',
            field=models.CharField(help_text='Title/name of the attachment', max_length=200),
        ),
    ]
