# Generated by Django 5.2.7 on 2025-12-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_lessonattachment_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecancellationrequest',
            name='reason',
            field=models.TextField(blank=True, default='', help_text="Optional: Student's explanation for cancellation/reschedule"),
        ),
    ]
