# Generated by Django 5.2.7 on 2025-12-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_make_cancellation_fields_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='content_rating',
            field=models.CharField(choices=[('G', 'General - Suitable for all ages'), ('PG', 'Parental Guidance - Some content may need parent explanation'), ('13', 'Ages 13+ - Content not suitable for younger children'), ('16', 'Ages 16+ - Mature content themes'), ('18', 'Adults Only (18+) - Not suitable for minors')], default='G', help_text='Age-appropriateness rating based on content themes (moral/safety, not difficulty)', max_length=3),
        ),
        migrations.AddField(
            model_name='course',
            name='content_warnings',
            field=models.TextField(blank=True, help_text='Optional: Specific content warnings (e.g., "Contains historical art with nudity", "Discusses war and conflict")'),
        ),
    ]
