# Generated by Django 5.2.9 on 2026-02-23 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_userprofile_workshop_email_notifications'),
        ('courses', '0020_add_content_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseenrollment',
            name='child_profile',
            field=models.ForeignKey(blank=True, help_text='If for a child, link to their child profile', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='accounts.childprofile'),
        ),
    ]
