# Generated by Django 5.2.9 on 2026-02-23 11:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_alter_courseenrollment_child_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['instructor', 'created_at'], name='courses_cou_instruc_f1fbcf_idx'),
        ),
    ]
