# Generated by Django 5.2.7 on 2025-10-24 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, help_text='Session key for anonymous users', max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='User who owns this cart', on_delete=django.db.models.deletion.CASCADE, related_name='lesson_cart', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shopping Cart',
                'verbose_name_plural': 'Shopping Carts',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(help_text='Student who submitted this request', on_delete=django.db.models.deletion.CASCADE, related_name='lesson_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lesson Request',
                'verbose_name_plural': 'Lesson Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonRequestMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Message content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(help_text='User who wrote this message (student or teacher)', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lesson_request', models.ForeignKey(help_text='The lesson request this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='private_teaching.lessonrequest')),
            ],
            options={
                'verbose_name': 'Lesson Request Message',
                'verbose_name_plural': 'Lesson Request Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(help_text='Unique order identifier', max_length=20, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total order amount', max_digits=8)),
                ('payment_status', models.CharField(choices=[('pending', 'Payment Pending'), ('completed', 'Payment Completed'), ('failed', 'Payment Failed'), ('refunded', 'Refunded')], default='pending', help_text='Payment processing status', max_length=20)),
                ('payment_method', models.CharField(default='simulation', help_text='Payment method used', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When payment was completed', null=True)),
                ('student', models.ForeignKey(help_text='Student who made the purchase', on_delete=django.db.models.deletion.CASCADE, related_name='lesson_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_paid', models.DecimalField(decimal_places=2, help_text='Price paid for this lesson', max_digits=8)),
                ('lesson', models.OneToOneField(help_text='Lesson purchased', on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='lessons.lesson')),
                ('order', models.ForeignKey(help_text='Order this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='private_teaching.order')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'ordering': ['order__created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price at time of adding to cart', max_digits=8)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(help_text='Cart this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='private_teaching.cart')),
                ('lesson', models.ForeignKey(help_text='Lesson to purchase', on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='lessons.lesson')),
            ],
            options={
                'verbose_name': 'Cart Item',
                'verbose_name_plural': 'Cart Items',
                'ordering': ['added_at'],
                'unique_together': {('cart', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_price_60min', models.DecimalField(decimal_places=2, default=50.0, help_text='Base price for 60-minute lesson', max_digits=6)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this subject is currently offered')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(help_text='Teacher who offers this subject', on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['subject'],
                'unique_together': {('teacher', 'subject')},
            },
        ),
    ]
