# Generated by Django 5.2.7 on 2025-10-28 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_child_profile_model'),
        ('private_teaching', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonrequest',
            name='child_profile',
            field=models.ForeignKey(blank=True, help_text='If requesting lessons for a child, link to their child profile', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_requests', to='accounts.childprofile'),
        ),
        migrations.AlterField(
            model_name='lessonrequest',
            name='student',
            field=models.ForeignKey(help_text='For adults: the student. For children: the guardian/parent.', on_delete=django.db.models.deletion.CASCADE, related_name='lesson_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='lessonrequest',
            index=models.Index(fields=['student', 'created_at'], name='private_tea_student_3ea38a_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonrequest',
            index=models.Index(fields=['child_profile', 'created_at'], name='private_tea_child_p_de9f37_idx'),
        ),
    ]
