# Generated by Django 5.2.7 on 2025-10-29 04:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_accepting_new_private_students_and_more'),
        ('private_teaching', '0002_add_child_profile_to_lesson_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherStudentApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('accepted', 'Accepted'), ('waitlist', 'On Waiting List'), ('declined', 'Declined')], default='pending', help_text='Current status of the application', max_length=20)),
                ('teacher_notes', models.TextField(blank=True, help_text='Private notes from teacher (reason for decline, waiting list notes, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('applicant', models.ForeignKey(help_text='Guardian/parent or adult student applying', on_delete=django.db.models.deletion.CASCADE, related_name='private_teaching_applications', to=settings.AUTH_USER_MODEL)),
                ('child_profile', models.ForeignKey(blank=True, help_text='If applying for a child, link to their child profile', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private_teaching_applications', to='accounts.childprofile')),
                ('teacher', models.ForeignKey(help_text='Teacher being applied to', on_delete=django.db.models.deletion.CASCADE, related_name='student_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher-Student Application',
                'verbose_name_plural': 'Teacher-Student Applications',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(help_text='Message content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(help_text='User who wrote this message (applicant or teacher)', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(help_text='The application this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='private_teaching.teacherstudentapplication')),
            ],
            options={
                'verbose_name': 'Application Message',
                'verbose_name_plural': 'Application Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='teacherstudentapplication',
            index=models.Index(fields=['teacher', 'status'], name='private_tea_teacher_4ce8dd_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherstudentapplication',
            index=models.Index(fields=['applicant', 'status'], name='private_tea_applica_ee6d20_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teacherstudentapplication',
            unique_together={('applicant', 'child_profile', 'teacher')},
        ),
    ]
