# Generated by Django 5.2.7 on 2025-11-12 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_accepting_new_private_students_and_more'),
        ('private_teaching', '0005_order_stripe_checkout_session_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonrequest',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when payment was completed', null=True),
        ),
        migrations.AddField(
            model_name='lessonrequest',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount paid or to be paid', max_digits=10),
        ),
        migrations.AddField(
            model_name='lessonrequest',
            name='payment_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending Payment'), ('completed', 'Payment Completed'), ('failed', 'Payment Failed')], default='not_required', help_text='Current payment status', max_length=20),
        ),
        migrations.AddField(
            model_name='lessonrequest',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, help_text='Stripe Checkout Session ID', max_length=255),
        ),
        migrations.AddField(
            model_name='lessonrequest',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, help_text='Stripe PaymentIntent ID for tracking', max_length=255),
        ),
        migrations.AlterField(
            model_name='lessonrequest',
            name='child_profile',
            field=models.ForeignKey(blank=True, help_text='If for a child, link to their child profile', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.childprofile'),
        ),
    ]
