# Generated by Django 5.2.7 on 2025-11-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_teaching', '0006_lessonrequest_paid_at_lessonrequest_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonrequestmessage',
            name='is_read',
            field=models.BooleanField(default=False, help_text='Whether this message has been read'),
        ),
        migrations.AddField(
            model_name='lessonrequestmessage',
            name='read_at',
            field=models.DateTimeField(blank=True, help_text='When this message was read', null=True),
        ),
    ]
