# Generated by Django 5.2.7 on 2025-11-21 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_lesson_exam_registration'),
        ('private_teaching', '0008_examboard_examregistration_exampiece_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateLessonTermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(help_text='Version number (e.g., 1, 2, 3)', unique=True)),
                ('content', models.TextField(help_text='Full Terms and Conditions text (supports Markdown)')),
                ('effective_date', models.DateTimeField(help_text='When these terms become effective')),
                ('is_current', models.BooleanField(default=False, help_text='Is this the current active version?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_private_lesson_terms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Private Lesson Terms and Conditions',
                'verbose_name_plural': 'Private Lesson Terms and Conditions',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='PrivateLessonTermsAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent string')),
                ('lesson', models.OneToOneField(blank=True, help_text='The lesson this acceptance is associated with', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terms_acceptance', to='lessons.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_lesson_terms_acceptances', to=settings.AUTH_USER_MODEL)),
                ('terms_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acceptances', to='private_teaching.privatelessontermsandconditions')),
            ],
            options={
                'verbose_name': 'Private Lesson Terms Acceptance',
                'verbose_name_plural': 'Private Lesson Terms Acceptances',
                'ordering': ['-accepted_at'],
            },
        ),
    ]
