# Generated by Django 5.2.7 on 2025-11-21 12:34

from django.db import migrations
from django.utils import timezone


def seed_initial_terms(apps, schema_editor):
    """Create initial Private Lesson Terms and Conditions"""
    PrivateLessonTermsAndConditions = apps.get_model('private_teaching', 'PrivateLessonTermsAndConditions')

    # The full T&Cs content with markdown formatting
    terms_content = """# Private Lesson Terms and Conditions

**Version:** 1.0

## 1. Acceptance of Terms

By booking a private lesson through Recorder-ed, you agree to these Terms and Conditions. These terms govern all private lesson bookings between students (or their parents/guardians) and teachers on our platform.

## 2. Booking and Payment

### 2.1 Lesson Booking
- Students may book individual lessons or purchase multiple lessons in advance
- All bookings must be made through the Recorder-ed platform
- Lesson times are confirmed when both teacher and student agree

### 2.2 Payment
- Payment is required at the time of booking
- Prices are set by individual teachers and displayed clearly before booking
- All payments are processed securely through our payment provider
- The platform fee is **non-refundable** in all circumstances

### 2.3 Lesson Packages
- Students may purchase multiple lessons at once
- Pre-paid lessons remain valid for use with the same teacher
- Unused lessons can be refunded in accordance with Section 4 (Cancellation Policy)

## 3. Lesson Delivery

### 3.1 Online Lessons
- Lessons are conducted via the platform's integrated video system or teacher's specified platform
- Students are responsible for having a stable internet connection and appropriate device
- Technical requirements will be communicated by the teacher in advance

### 3.2 In-Person Lessons
- Location will be specified by the teacher at time of booking
- Students must arrive on time; late arrivals may result in shortened lessons
- Students must follow any venue-specific rules or requirements

### 3.3 Lesson Duration
- Lessons are conducted for the duration specified at booking
- Teachers are not obligated to extend lessons due to student lateness or technical issues on the student's side

## 4. Cancellation and Refund Policy

### 4.1 Student Cancellations - Advance Notice (48+ Hours)
If a student cancels with **48 hours or more notice** before the scheduled lesson:
- **Option 1 (Preferred):** Reschedule the lesson to a mutually agreed time - no refund needed
- **Option 2:** If rescheduling is not possible, receive a full refund minus the non-refundable platform fee
- There is no limit on the number of times a lesson can be rescheduled

### 4.2 Student Cancellations - Short Notice (Less than 48 Hours)
If a student cancels with **less than 48 hours notice**:
- **No refund** will be issued
- Full lesson fee is paid to the teacher
- Rescheduling is only available at the teacher's discretion

### 4.3 No-Show Policy
If a student fails to attend a scheduled lesson without prior cancellation:
- **No refund** will be issued
- Full lesson fee is paid to the teacher
- This is treated the same as a cancellation with less than 48 hours notice

### 4.4 Emergency Exceptions
In cases of genuine emergency (serious illness, family emergency, bereavement):
- Teachers may choose to offer a refund or reschedule at their discretion, even with short notice
- Students should contact their teacher as soon as possible to explain the situation
- Emergency refund requests are subject to teacher approval and platform review

### 4.5 Discontinuing Lessons
If a student wishes to discontinue all lessons with a teacher:
- All future scheduled lessons beyond 48 hours can be cancelled with full refund (minus platform fee)
- Lessons scheduled within the 48-hour window are non-refundable
- Any pre-paid unused lessons can be refunded if proper 48-hour notice is given for each lesson

### 4.6 Teacher Cancellations
If a teacher cancels a lesson for any reason:
- **Student's choice:** Full refund (including platform fee) OR reschedule to another time
- No penalty to the student
- Platform will assist in finding alternative arrangements if needed

### 4.7 Technical Issues
- **Platform or teacher technical issues:** Full refund or reschedule at student's choice
- **Student technical issues:** Standard cancellation policy applies (48-hour rule)
- If a lesson is interrupted by technical issues, teacher and student should attempt to reschedule the remainder

### 4.8 Refund Request Timeframe
- **Advance cancellations** (48+ hours before lesson): Can be requested any time before the lesson
- **Post-lesson refund requests**: Must be made within **14 days** of the scheduled lesson date
- Requests after 14 days will not be processed

### 4.9 How to Request Cancellations/Refunds
- All cancellation and refund requests must be made through the Recorder-ed platform
- Email or verbal cancellations to teachers are not sufficient
- Students will receive confirmation of their cancellation request

## 5. Lesson Content and Quality

### 5.1 Lesson Content
- Teachers determine lesson content based on student level and goals
- No guarantee is made regarding specific outcomes or progress
- Different teaching approaches work for different students

### 5.2 No Refunds for Subjective Reasons
Refunds will **not** be issued because:
- Student found the lesson "too difficult" or "too easy"
- Student didn't like the teaching style
- Student didn't achieve expected progress
- Student changed their mind about learning

### 5.3 Legitimate Complaints
If you have serious concerns about lesson quality or teacher conduct:
- Contact Recorder-ed support immediately
- We will investigate and take appropriate action
- Refunds may be issued in cases of serious misconduct or breach of terms

## 6. Student and Teacher Responsibilities

### 6.1 Student Responsibilities
- Attend lessons on time with necessary materials
- Provide a suitable learning environment
- Treat teachers with respect
- Practice between lessons as recommended
- Communicate any issues or concerns promptly

### 6.2 Teacher Responsibilities
- Deliver lessons professionally and on time
- Provide clear communication about lesson content and expectations
- Maintain appropriate conduct at all times
- Honor the cancellation and refund policy

## 7. Age, Parental Consent, and Safeguarding

### 7.1 Minors
- Students under 18 must have parent/guardian consent to book lessons
- Parents/guardians are responsible for all bookings and payments
- Parents should be present or nearby during online lessons with children under 13
- For in-person lessons with minors, parents should ensure appropriate supervision

### 7.2 Background Checks for Teachers of Minors
- **All teachers who teach students under 18 must provide a valid background check**
- **UK-based teachers:** Must provide an Enhanced DBS (Disclosure and Barring Service) check
- **Non-UK teachers:** Must provide the equivalent government-issued criminal background check from their country of residence (e.g., FBI background check for US teachers, Police Clearance Certificate for other countries)
- Background checks are verified before teachers are approved to teach minors on the platform
- Teachers who do not provide a valid background check are **only permitted to teach students aged 18 and over**
- **Teacher profiles clearly display a verification badge** indicating the teacher is background-checked and approved to teach minors

### 7.3 Safeguarding Policy
- Recorder-ed is committed to the safeguarding and protection of all children and vulnerable adults
- All teachers must adhere to our Safeguarding Policy
- Teachers must maintain appropriate professional boundaries at all times
- One-to-one lessons with minors should take place in appropriate settings with parental awareness

### 7.4 Reporting Safeguarding Concerns
- Any safeguarding concerns must be reported immediately to Recorder-ed support
- Reports will be taken seriously and investigated promptly
- We will work with parents and relevant authorities as appropriate
- Suspected abuse or serious safeguarding breaches will be reported to police and social services

### 7.5 Parent/Guardian Rights
- Parents have the right to observe lessons (with advance notice to the teacher)
- Parents should know the lesson location and timing for all in-person lessons
- Clear communication between parents and teachers is encouraged
- Parents should feel empowered to ask questions about lesson content and approach

## 8. Platform Fees and Teacher Payments

### 8.1 Platform Fee
- Recorder-ed charges a platform fee on all lesson bookings
- This fee covers platform operation, payment processing, and support services
- **Platform fees are non-refundable**, even if the lesson fee is refunded

### 8.2 Teacher Payments
- Teachers receive their portion after the lesson is completed
- Refunds for cancelled lessons are deducted from teacher payments
- Teachers are paid according to the platform's payment schedule

## 9. Data Protection and Privacy

### 9.1 Personal Information
- We collect and process personal data in accordance with GDPR
- Your data is used only for lesson booking and platform operations
- See our Privacy Policy for full details

### 9.2 Recording Lessons
- Lessons should not be recorded without explicit consent from both parties
- Any recordings must comply with data protection laws

## 10. Liability and Disclaimers

### 10.1 Platform Role
- Recorder-ed is a platform connecting students and teachers
- We facilitate bookings but do not directly provide lessons
- Teachers are independent contractors, not employees

### 10.2 Limitation of Liability
- We are not liable for the quality or outcomes of lessons
- Our liability is limited to the amount paid for the affected lesson
- We are not responsible for indirect or consequential losses

### 10.3 Teacher Conduct
- While we vet teachers, we cannot guarantee their performance
- Report any concerns immediately to platform support
- We will investigate complaints and take appropriate action

## 11. Disputes and Resolution

### 11.1 Dispute Process
1. Contact your teacher first to resolve issues directly
2. If unresolved, contact Recorder-ed support within 14 days
3. We will mediate and make a final decision
4. Platform decisions on refunds are final

### 11.2 Evidence
- Keep records of communications with teachers
- Take screenshots of technical issues if they occur
- Provide evidence when requesting refunds for problems

## 12. Changes to Terms

### 12.1 Updates
- We may update these terms from time to time
- Changes will be posted with a new version number and effective date
- Continued use of the platform indicates acceptance of updated terms

### 12.2 Existing Bookings
- Changes to terms do not affect lessons already booked
- Existing bookings remain under the terms accepted at booking time

## 13. Governing Law

These terms are governed by the laws of England and Wales. Any disputes will be subject to the exclusive jurisdiction of the courts of England and Wales.

## 14. Contact Information

For questions about these terms or to report issues:
- Email: support@recorder-ed.com
- Use the support ticket system on our platform
- Response time: Within 2 business days

---

**By booking a private lesson, you confirm that you have read, understood, and agree to these Terms and Conditions.**
"""

    # Create the initial terms
    PrivateLessonTermsAndConditions.objects.create(
        version=1,
        content=terms_content,
        effective_date=timezone.now(),
        is_current=True,
        created_by=None  # No user during migration
    )


def reverse_seed(apps, schema_editor):
    """Remove the initial terms"""
    PrivateLessonTermsAndConditions = apps.get_model('private_teaching', 'PrivateLessonTermsAndConditions')
    PrivateLessonTermsAndConditions.objects.filter(version=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('private_teaching', '0009_privatelessontermsandconditions_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_initial_terms, reverse_seed),
    ]
