# Generated by Django 5.2.7 on 2025-11-21 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_lesson_exam_registration'),
        ('private_teaching', '0010_seed_initial_private_lesson_terms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonCancellationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('cancel_refund', 'Cancel with Refund'), ('reschedule', 'Reschedule Lesson')], default='cancel_refund', max_length=20)),
                ('cancellation_reason', models.CharField(choices=[('schedule_conflict', 'Schedule Conflict'), ('illness', 'Illness'), ('emergency', 'Family Emergency'), ('no_longer_needed', 'No Longer Need Lessons'), ('discontinuing', 'Discontinuing All Lessons'), ('other', 'Other')], max_length=30)),
                ('student_message', models.TextField(help_text="Student's explanation for the cancellation/reschedule request")),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('hours_before_lesson', models.DecimalField(decimal_places=2, help_text='Hours between request and lesson start time', max_digits=6)),
                ('is_within_policy', models.BooleanField(default=True, help_text='True if requested 48+ hours before lesson (eligible for refund)')),
                ('status', models.CharField(choices=[('pending', 'Pending Teacher Decision'), ('approved', 'Approved by Teacher'), ('rejected', 'Rejected by Teacher'), ('completed', 'Completed (Refunded/Rescheduled)')], default='pending', max_length=20)),
                ('teacher_response', models.TextField(blank=True, help_text="Teacher's response to the request")),
                ('teacher_responded_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount to be refunded (lesson price minus platform fee)', max_digits=8, null=True)),
                ('platform_fee_retained', models.DecimalField(blank=True, decimal_places=2, help_text='Platform fee that is non-refundable', max_digits=8, null=True)),
                ('refund_processed_at', models.DateTimeField(blank=True, null=True)),
                ('proposed_new_date', models.DateField(blank=True, null=True)),
                ('proposed_new_time', models.TimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_requests', to='lessons.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_cancellation_requests', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_cancellation_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lesson Cancellation Request',
                'verbose_name_plural': 'Lesson Cancellation Requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
