# Generated by Django 5.2.7 on 2025-11-21 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """
    Refactor LessonCancellationRequest to inherit from BaseCancellationRequest.

    This migration:
    1. Renames requested_at → created_at (inherited from base)
    2. Renames student_message → reason (inherited from base)
    3. Adds new fields from BaseCancellationRequest: updated_at, admin_notes,
       reviewed_by, reviewed_at, is_eligible_for_refund
    """

    dependencies = [
        ('private_teaching', '0011_lessoncancellationrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Rename requested_at to created_at
        migrations.RenameField(
            model_name='lessoncancellationrequest',
            old_name='requested_at',
            new_name='created_at',
        ),
        # Rename student_message to reason
        migrations.RenameField(
            model_name='lessoncancellationrequest',
            old_name='student_message',
            new_name='reason',
        ),
        # Add updated_at field
        migrations.AddField(
            model_name='lessoncancellationrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        # Add admin_notes field
        migrations.AddField(
            model_name='lessoncancellationrequest',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Admin notes/response'),
        ),
        # Add reviewed_by field
        migrations.AddField(
            model_name='lessoncancellationrequest',
            name='reviewed_by',
            field=models.ForeignKey(
                blank=True,
                help_text='Admin who reviewed this request',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='private_teaching_lessoncancellationrequest_reviewed',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        # Add reviewed_at field
        migrations.AddField(
            model_name='lessoncancellationrequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        # Add is_eligible_for_refund field
        migrations.AddField(
            model_name='lessoncancellationrequest',
            name='is_eligible_for_refund',
            field=models.BooleanField(
                default=False,
                help_text='Is this cancellation eligible for refund?'
            ),
        ),
        # Update Meta ordering to use created_at instead of requested_at
        migrations.AlterModelOptions(
            name='lessoncancellationrequest',
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Lesson Cancellation Request',
                'verbose_name_plural': 'Lesson Cancellation Requests'
            },
        ),
    ]
