# Generated by Django 5.2.7 on 2025-11-22 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_teaching', '0012_refactor_to_base_cancellation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessoncancellationrequest',
            name='reason',
            field=models.TextField(help_text="Student's reason for cancellation"),
        ),
        migrations.AlterField(
            model_name='lessoncancellationrequest',
            name='refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount to be refunded', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='lessoncancellationrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Admin who reviewed this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lessoncancellationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed (Refund Processed)')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='lessoncancellationrequest',
            name='student',
            field=models.ForeignKey(help_text='Student requesting cancellation', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
