# Generated by Django 5.2.7 on 2025-11-23 15:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_userprofile_age_groups_taught_and_more'),
        ('private_teaching', '0013_alter_lessoncancellationrequest_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('practice_date', models.DateField(help_text='Date of practice session')),
                ('duration_minutes', models.PositiveIntegerField(help_text='How long practiced (in minutes)')),
                ('pieces_practiced', models.TextField(blank=True, help_text="Pieces/songs worked on (e.g., 'Sonata in F, Scales: G Major, A Minor')")),
                ('exercises_practiced', models.TextField(blank=True, help_text="Technical exercises (e.g., 'Long tones, Tonguing exercises')")),
                ('focus_areas', models.TextField(blank=True, help_text="What you focused on (e.g., 'Worked on tricky section bars 12-16')")),
                ('struggles', models.TextField(blank=True, help_text='Difficulties encountered (optional)')),
                ('achievements', models.TextField(blank=True, help_text='Breakthroughs or improvements (optional)')),
                ('enjoyment_rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 - Not enjoyable'), (2, '2'), (3, '3'), (4, '4'), (5, '5 - Very enjoyable')], help_text='How enjoyable was this practice session?', null=True)),
                ('preparing_for_exam', models.BooleanField(default=False, help_text='Check if practicing for an upcoming exam')),
                ('preparing_for_performance', models.BooleanField(default=False, help_text='Check if practicing for a recital or performance')),
                ('teacher_comment', models.TextField(blank=True, help_text="Teacher's comment on this practice session (optional)")),
                ('teacher_viewed_at', models.DateTimeField(blank=True, help_text='When teacher viewed this entry', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child_profile', models.ForeignKey(blank=True, help_text="If practicing for a child's lessons", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practice_entries', to='accounts.childprofile')),
                ('lesson_request', models.ForeignKey(blank=True, help_text='Associated lesson request/relationship', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practice_entries', to='private_teaching.lessonrequest')),
                ('student', models.ForeignKey(help_text='Student who practiced (adult or guardian for child)', on_delete=django.db.models.deletion.CASCADE, related_name='practice_entries', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(help_text='Teacher who can view this practice entry', on_delete=django.db.models.deletion.CASCADE, related_name='student_practice_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Practice Entry',
                'verbose_name_plural': 'Practice Entries',
                'ordering': ['-practice_date', '-created_at'],
                'indexes': [models.Index(fields=['student', '-practice_date'], name='private_tea_student_11a599_idx'), models.Index(fields=['teacher', '-practice_date'], name='private_tea_teacher_1cef4c_idx')],
            },
        ),
    ]
