# Generated by Django 5.2.7 on 2025-11-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_teaching', '0014_practiceentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['display_order', 'subject'], 'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
        migrations.AddField(
            model_name='subject',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Order in which subjects are displayed (lower numbers appear first)'),
        ),
    ]
