# Generated by Django 5.2.7 on 2025-12-10 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioplayer', '0002_composer_tag_piece_description_piece_difficulty_and_more'),
        ('private_teaching', '0015_add_subject_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampiece',
            name='playalong_piece',
            field=models.ForeignKey(blank=True, help_text='Link to playalong piece for practice', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_pieces', to='audioplayer.piece'),
        ),
    ]
