# Generated by Django 5.2.7 on 2025-12-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_teaching', '0016_exampiece_playalong_piece'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessoncancellationrequest',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('schedule_conflict', 'Schedule Conflict'), ('illness', 'Illness'), ('emergency', 'Family Emergency'), ('no_longer_needed', 'No Longer Need Lessons'), ('discontinuing', 'Discontinuing All Lessons'), ('other', 'Other')], default=None, help_text="Optional: Student can provide a reason, but it's not required", max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lessoncancellationrequest',
            name='reason',
            field=models.TextField(blank=True, default='', help_text="Optional: Student's explanation for cancellation/reschedule"),
        ),
    ]
