# Generated by Django 5.2.7 on 2025-12-21 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_teaching', '0017_make_cancellation_fields_optional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAvailabilitySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buffer_minutes', models.IntegerField(default=0, help_text='Minutes of break time required between lessons (0-60)')),
                ('min_booking_notice_hours', models.IntegerField(default=24, help_text='Minimum hours in advance students must book (e.g., 24 = must book at least 1 day ahead)')),
                ('max_booking_days_ahead', models.IntegerField(default=90, help_text='Maximum days in advance students can book (e.g., 90 = can book up to 3 months ahead)')),
                ('use_availability_calendar', models.BooleanField(default=False, help_text='Enable availability calendar (if False, uses old request system)')),
                ('auto_approve_bookings', models.BooleanField(default=True, help_text='Automatically approve bookings if slot is available (recommended)')),
                ('timezone', models.CharField(default='UTC', help_text="Teacher's timezone (e.g., 'America/New_York', 'Europe/London')", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.OneToOneField(help_text='Teacher who owns these settings', on_delete=django.db.models.deletion.CASCADE, related_name='availability_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher Availability Settings',
                'verbose_name_plural': 'Teacher Availability Settings',
                'db_table': 'private_teaching_availability_settings',
            },
        ),
        migrations.CreateModel(
            name='AvailabilityException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception_type', models.CharField(choices=[('block', 'Block Time (Unavailable)'), ('available', 'Add Availability (Override)')], default='block', help_text='Type of exception: block unavailable time or add special availability', max_length=20)),
                ('date', models.DateField(help_text='Specific date for this exception')),
                ('start_time', models.TimeField(blank=True, help_text='Start time (leave blank to block entire day)', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='End time (leave blank to block entire day)', null=True)),
                ('reason', models.CharField(blank=True, help_text="Optional reason (e.g., 'Christmas Holiday', 'Conference')", max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Set to False to cancel this exception')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(help_text='Teacher who owns this exception', on_delete=django.db.models.deletion.CASCADE, related_name='availability_exceptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Availability Exception',
                'verbose_name_plural': 'Availability Exceptions',
                'db_table': 'private_teaching_availability_exception',
                'ordering': ['date', 'start_time'],
                'indexes': [models.Index(fields=['teacher', 'date'], name='private_tea_teacher_2394e5_idx')],
            },
        ),
        migrations.CreateModel(
            name='TeacherAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of week (0=Monday, 6=Sunday)')),
                ('start_time', models.TimeField(help_text='Start time of availability (e.g., 09:00)')),
                ('end_time', models.TimeField(help_text='End time of availability (e.g., 17:00)')),
                ('is_active', models.BooleanField(default=True, help_text='Set to False to temporarily disable this slot')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(help_text='Teacher who owns this availability slot', on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher Availability Slot',
                'verbose_name_plural': 'Teacher Availability Slots',
                'db_table': 'private_teaching_teacher_availability',
                'ordering': ['day_of_week', 'start_time'],
                'indexes': [models.Index(fields=['teacher', 'day_of_week'], name='private_tea_teacher_48e31d_idx')],
            },
        ),
    ]
