# Generated by Django 5.2.7 on 2025-12-21 18:52

from django.db import migrations


def create_default_settings(apps, schema_editor):
    """
    Create default availability settings for all existing teachers
    """
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('accounts', 'UserProfile')
    TeacherAvailabilitySettings = apps.get_model('private_teaching', 'TeacherAvailabilitySettings')

    # Get all users who are teachers
    teacher_profiles = UserProfile.objects.filter(is_teacher=True)
    teacher_ids = teacher_profiles.values_list('user_id', flat=True)
    teachers = User.objects.filter(id__in=teacher_ids)

    for teacher in teachers:
        TeacherAvailabilitySettings.objects.get_or_create(
            teacher=teacher,
            defaults={
                'use_availability_calendar': False,  # Start disabled, teachers opt-in
                'buffer_minutes': 0,
                'min_booking_notice_hours': 24,
                'max_booking_days_ahead': 90,
                'auto_approve_bookings': True,
                'timezone': 'UTC',
            }
        )


def reverse_default_settings(apps, schema_editor):
    """
    Remove all availability settings (for migration rollback)
    """
    TeacherAvailabilitySettings = apps.get_model('private_teaching', 'TeacherAvailabilitySettings')
    TeacherAvailabilitySettings.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('private_teaching', '0018_add_teacher_availability_models'),
        ('accounts', '__latest__'),  # Ensure accounts app migrations are applied
        ('auth', '__latest__'),  # Ensure auth app migrations are applied
    ]

    operations = [
        migrations.RunPython(create_default_settings, reverse_default_settings),
    ]
