# Generated by Django 5.2.9 on 2025-12-26 14:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
        ('lessons', '0006_lesson_exam_registration'),
        ('private_teaching', '0019_create_default_availability_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateLessonAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('due_date', models.DateTimeField(blank=True, help_text='Optional due date for the assignment', null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_lesson_assignments', to='assignments.assignment')),
                ('lesson', models.ForeignKey(blank=True, help_text='Optional: Link to specific lesson', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='lessons.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_lesson_assignments_received', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_lesson_assignments_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['student', '-assigned_at'], name='private_tea_student_af79d9_idx'), models.Index(fields=['teacher', '-assigned_at'], name='private_tea_teacher_721dc1_idx'), models.Index(fields=['lesson'], name='private_tea_lesson__92c330_idx')],
            },
        ),
    ]
