# Generated by Django 5.2.9 on 2025-12-27 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_userprofile_workshop_email_notifications'),
        ('private_teaching', '0020_privatelessonassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatelessonassignment',
            name='child_profile',
            field=models.ForeignKey(blank=True, help_text='Optional: Specific child this assignment is for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments_received', to='accounts.childprofile'),
        ),
    ]
