# Generated by Django 5.2.9 on 2025-12-27 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_add_lesson_assignments'),
        ('private_teaching', '0021_add_child_profile_to_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatelessonassignment',
            name='lesson',
            field=models.ForeignKey(blank=True, help_text='Optional: Link to specific lesson (DEPRECATED)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_assignment_links', to='lessons.lesson'),
        ),
    ]
