# Generated by Django 5.2.9 on 2025-12-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_teaching', '0022_rename_assignment_related_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacheravailabilitysettings',
            name='max_recurring_lessons',
            field=models.IntegerField(default=8, help_text='Maximum number of lessons students can book in a recurring sequence (e.g., 8 = up to 8 weekly lessons)'),
        ),
    ]
