# Generated by Django 5.2.9 on 2026-01-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_teaching', '0024_privatelessonquiz_privatelessonquizassignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatelessonquizattempt',
            name='last_autosave_at',
            field=models.DateTimeField(
                null=True,
                blank=True,
                help_text='Timestamp of last auto-save operation'
            ),
        ),
    ]
