# Generated by Django 5.2.9 on 2026-01-09 09:25

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('private_teaching', '0025_add_quiz_autosave_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatelessonquizanswer',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Answer text (supports images, formatting, music notation)'),
        ),
    ]
