# Generated by Django 5.2.9 on 2026-01-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_teaching', '0026_alter_privatelessonquizanswer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatelessonquiz',
            name='pagination_mode',
            field=models.CharField(choices=[('continuous', 'Continuous (Single Page)'), ('paginated', 'Paginated (One at a Time)')], default='continuous', help_text='Display mode for quiz questions', max_length=20),
        ),
    ]
