# Generated by Django 5.2.9 on 2026-01-20 06:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioplayer', '0007_piece_created_by'),
        ('lessons', '0010_lesson_lesson_teacher_schedule_idx_and_more'),
        ('private_teaching', '0027_privatelessonquiz_pagination_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='applicationmessage',
            index=models.Index(fields=['application', 'created_at'], name='private_tea_applica_256d32_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart', 'added_at'], name='private_tea_cart_id_f2f8ea_idx'),
        ),
        migrations.AddIndex(
            model_name='exampiece',
            index=models.Index(fields=['exam_registration', 'piece_number'], name='private_tea_exam_re_40107e_idx'),
        ),
        migrations.AddIndex(
            model_name='lessoncancellationrequest',
            index=models.Index(fields=['teacher', 'status'], name='private_tea_teacher_a05cfb_idx'),
        ),
        migrations.AddIndex(
            model_name='lessoncancellationrequest',
            index=models.Index(fields=['student', '-created_at'], name='private_tea_student_2047c4_idx'),
        ),
        migrations.AddIndex(
            model_name='lessoncancellationrequest',
            index=models.Index(fields=['lesson'], name='private_tea_lesson__fcb69e_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonrequestmessage',
            index=models.Index(fields=['lesson_request', 'created_at'], name='private_tea_lesson__660050_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['student', '-created_at'], name='private_tea_student_0ea97b_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status', '-created_at'], name='private_tea_payment_82af5c_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='private_tea_order_i_8c4af8_idx'),
        ),
    ]
