# Generated by Django 5.2.9 on 2026-02-13 16:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_userprofile_workshop_email_notifications'),
        ('audioplayer', '0011_alter_stem_audio_file'),
        ('private_teaching', '0028_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCollectionAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=20)),
                ('instructions', models.TextField(blank=True, help_text='Practice instructions for this collection')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('child_profile', models.ForeignKey(blank=True, help_text='Optional: Specific child this collection is for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_collections', to='accounts.childprofile')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='audioplayer.piececollection')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_collections', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_assignments_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['student', 'status'], name='private_tea_student_e299e8_idx'), models.Index(fields=['teacher', '-assigned_at'], name='private_tea_teacher_c272f9_idx')],
                'unique_together': {('student', 'collection', 'teacher')},
            },
        ),
        migrations.CreateModel(
            name='StudentPieceAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=20)),
                ('instructions', models.TextField(blank=True, help_text='Practice instructions for this piece')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('child_profile', models.ForeignKey(blank=True, help_text='Optional: Specific child this piece is for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_pieces', to='accounts.childprofile')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='audioplayer.piece')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_pieces', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piece_assignments_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['student', 'status'], name='private_tea_student_31f7bd_idx'), models.Index(fields=['teacher', '-assigned_at'], name='private_tea_teacher_5529c0_idx')],
                'unique_together': {('student', 'piece', 'teacher')},
            },
        ),
    ]
