# Generated by Django 5.2.9 on 2026-02-23 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_userprofile_workshop_email_notifications'),
        ('private_teaching', '0029_studentcollectionassignment_studentpieceassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examregistration',
            name='child_profile',
            field=models.ForeignKey(blank=True, help_text='If for a child, link to their child profile', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='accounts.childprofile'),
        ),
        migrations.AlterField(
            model_name='lessonrequest',
            name='child_profile',
            field=models.ForeignKey(blank=True, help_text='If for a child, link to their child profile', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='accounts.childprofile'),
        ),
        migrations.AlterField(
            model_name='practiceentry',
            name='child_profile',
            field=models.ForeignKey(blank=True, help_text="If practicing for a child's lessons", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practice_entries', to='accounts.childprofile'),
        ),
        migrations.AlterField(
            model_name='privatelessonassignment',
            name='child_profile',
            field=models.ForeignKey(blank=True, help_text='Optional: Specific child this assignment is for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_received', to='accounts.childprofile'),
        ),
        migrations.AlterField(
            model_name='privatelessonquizassignment',
            name='child_profile',
            field=models.ForeignKey(blank=True, help_text='If student is a guardian, specify which child', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_quizzes', to='accounts.childprofile'),
        ),
        migrations.AlterField(
            model_name='studentcollectionassignment',
            name='child_profile',
            field=models.ForeignKey(blank=True, help_text='Optional: Specific child this collection is for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_collections', to='accounts.childprofile'),
        ),
        migrations.AlterField(
            model_name='studentpieceassignment',
            name='child_profile',
            field=models.ForeignKey(blank=True, help_text='Optional: Specific child this piece is for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pieces', to='accounts.childprofile'),
        ),
        migrations.AlterField(
            model_name='teacherstudentapplication',
            name='child_profile',
            field=models.ForeignKey(blank=True, help_text='If applying for a child, link to their child profile', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='private_teaching_applications', to='accounts.childprofile'),
        ),
    ]
