# Generated by Django 5.2.9 on 2026-02-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_teaching', '0030_alter_examregistration_child_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoncancellationrequest',
            name='initiated_by',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], default='student', help_text='Who initiated this request', max_length=10),
        ),
    ]
