# Generated by Django 5.2.9 on 2026-02-23 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('private_teaching', '0032_migrate_pla_to_la'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrivateLessonAssignment',
        ),
    ]
