# Generated by Django 4.2.28 on 2026-02-23 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0016_userprofile_workshop_email_notifications'),
        ('lessons', '0016_historicallesson'),
        ('private_teaching', '0038_remove_quiz_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTeacherStudentApplication',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('accepted', 'Accepted'), ('waitlist', 'On Waiting List'), ('declined', 'Declined')], default='pending', help_text='Current status of the application', max_length=20)),
                ('teacher_notes', models.TextField(blank=True, help_text='Private notes from teacher (reason for decline, waiting list notes, etc.)')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('applicant', models.ForeignKey(blank=True, db_constraint=False, help_text='Guardian/parent or adult student applying', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('child_profile', models.ForeignKey(blank=True, db_constraint=False, help_text='If applying for a child, link to their child profile', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.childprofile')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(blank=True, db_constraint=False, help_text='Teacher being applied to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Teacher-Student Application',
                'verbose_name_plural': 'historical Teacher-Student Applications',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalOrder',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, help_text='Unique order identifier', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total order amount', max_digits=8)),
                ('payment_status', models.CharField(choices=[('pending', 'Payment Pending'), ('completed', 'Payment Completed'), ('failed', 'Payment Failed'), ('refunded', 'Refunded')], default='pending', help_text='Payment processing status', max_length=20)),
                ('payment_method', models.CharField(default='stripe', help_text='Payment method used', max_length=50)),
                ('stripe_payment_intent_id', models.CharField(blank=True, help_text='Stripe PaymentIntent ID', max_length=255, null=True)),
                ('stripe_checkout_session_id', models.CharField(blank=True, help_text='Stripe Checkout Session ID', max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When payment was completed', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, db_constraint=False, help_text='Student who made the purchase', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Order',
                'verbose_name_plural': 'historical Orders',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalLessonCancellationRequest',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('reason', models.TextField(blank=True, default='', help_text="Optional: Student's explanation for cancellation/reschedule")),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed (Refund Processed)')], default='pending', max_length=20)),
                ('is_eligible_for_refund', models.BooleanField(default=False, help_text='Is this cancellation eligible for refund?')),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount to be refunded', max_digits=10, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes/response')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('refund_processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('initiated_by', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], default='student', help_text='Who initiated this request', max_length=10)),
                ('request_type', models.CharField(choices=[('cancel_refund', 'Cancel with Refund'), ('reschedule', 'Reschedule Lesson')], default='cancel_refund', max_length=20)),
                ('cancellation_reason', models.CharField(blank=True, choices=[('schedule_conflict', 'Schedule Conflict'), ('illness', 'Illness'), ('emergency', 'Family Emergency'), ('no_longer_needed', 'No Longer Need Lessons'), ('discontinuing', 'Discontinuing All Lessons'), ('other', 'Other')], default=None, help_text="Optional: Student can provide a reason, but it's not required", max_length=30, null=True)),
                ('hours_before_lesson', models.DecimalField(decimal_places=2, help_text='Hours between request and lesson start time', max_digits=6)),
                ('is_within_policy', models.BooleanField(default=True, help_text='True if requested 48+ hours before lesson (eligible for refund)')),
                ('teacher_response', models.TextField(blank=True, help_text="Teacher's response to the request")),
                ('teacher_responded_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('platform_fee_retained', models.DecimalField(blank=True, decimal_places=2, help_text='Platform fee that is non-refundable', max_digits=8, null=True)),
                ('proposed_new_date', models.DateField(blank=True, null=True)),
                ('proposed_new_time', models.TimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lessons.lesson')),
                ('reviewed_by', models.ForeignKey(blank=True, db_constraint=False, help_text='Admin who reviewed this request', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, db_constraint=False, help_text='Student requesting cancellation', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Lesson Cancellation Request',
                'verbose_name_plural': 'historical Lesson Cancellation Requests',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
