# Generated by Django 5.2.7 on 2025-10-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_order_user_remove_transaction_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripepayment',
            name='course_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stripepayment',
            name='workshop_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
