# Generated by Django 5.2.7 on 2025-10-30 19:43

from django.db import migrations, models


def clear_id_fields(apps, schema_editor):
    """Clear workshop_id and course_id before converting to UUID"""
    StripePayment = apps.get_model('payments', 'StripePayment')
    StripePayment.objects.all().update(workshop_id=None, course_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_order_user_remove_transaction_order_and_more'),
    ]

    operations = [
        # First clear the integer values
        migrations.RunPython(clear_id_fields, migrations.RunPython.noop),
        # Then change field types to UUID
        migrations.AlterField(
            model_name='stripepayment',
            name='course_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stripepayment',
            name='workshop_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
