# Generated by Django 5.2.7 on 2025-11-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_merge_20251030_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripepayment',
            name='refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount refunded (if partial)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stripepayment',
            name='refunded_at',
            field=models.DateTimeField(blank=True, help_text='When refund was processed', null=True),
        ),
        migrations.AddField(
            model_name='stripepayment',
            name='stripe_refund_id',
            field=models.CharField(blank=True, help_text='Stripe refund ID', max_length=255, null=True),
        ),
    ]
