# Generated by Django 5.2.7 on 2025-12-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_stripepayment_refund_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripepayment',
            name='domain',
            field=models.CharField(choices=[('workshops', 'Workshops'), ('courses', 'Courses'), ('private_teaching', 'Private Teaching'), ('digital_products', 'Digital Products')], max_length=50),
        ),
    ]
