# Generated by Django 5.2.9 on 2026-01-26 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_stripepayment_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripepayment',
            name='stripe_balance_transaction_id',
            field=models.CharField(blank=True, help_text='Stripe Balance Transaction ID for fee tracking', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stripepayment',
            name='stripe_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Stripe's processing fee for this transaction", max_digits=10, null=True),
        ),
    ]
