# Generated by Django 5.2.9 on 2026-02-05 08:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_add_stripe_fee_fields'),
        ('private_teaching', '0028_add_performance_indexes'),
        ('workshops', '0028_merge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='Unique voucher code (e.g., SUMMER25, FREECLASS)', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text="Internal description/purpose (e.g., 'Competition winner prize')")),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage Off'), ('fixed', 'Fixed Amount Off'), ('free', '100% Free')], help_text='Type of discount to apply', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, help_text="Percentage (0-100) or fixed amount in GBP depending on type. Set to 0 for 'free' type.", max_digits=10)),
                ('applicable_domains', models.JSONField(default=list, help_text="List of domains: ['private_teaching', 'workshops', 'workshop_series']")),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, help_text='When the voucher becomes valid')),
                ('valid_until', models.DateTimeField(blank=True, help_text='When the voucher expires (null = no expiration)', null=True)),
                ('max_uses_total', models.PositiveIntegerField(blank=True, help_text='Maximum total redemptions (null = unlimited)', null=True)),
                ('max_uses_per_student', models.PositiveIntegerField(default=1, help_text='Maximum uses per student')),
                ('minimum_purchase_amount', models.DecimalField(decimal_places=2, default=0, help_text='Minimum cart total required to apply voucher', max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('expired', 'Expired'), ('exhausted', 'Usage Limit Reached')], default='active', help_text='Current status of the voucher', max_length=20)),
                ('stripe_coupon_id', models.CharField(blank=True, help_text='Stripe Coupon ID for partial discount vouchers', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Teacher who created this voucher', on_delete=django.db.models.deletion.CASCADE, related_name='created_vouchers', to=settings.AUTH_USER_MODEL)),
                ('restricted_to_students', models.ManyToManyField(blank=True, help_text='If set, only these students can use the voucher', related_name='restricted_vouchers', to=settings.AUTH_USER_MODEL)),
                ('restricted_to_workshops', models.ManyToManyField(blank=True, help_text='If set, only valid for these specific workshops', related_name='restricted_vouchers', to='workshops.workshop')),
            ],
            options={
                'verbose_name': 'Voucher',
                'verbose_name_plural': 'Vouchers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoucherRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(help_text='Domain where voucher was used: private_teaching, workshops, workshop_series', max_length=50)),
                ('original_amount', models.DecimalField(decimal_places=2, help_text='Original price before discount', max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, help_text='Amount discounted', max_digits=10)),
                ('final_amount', models.DecimalField(decimal_places=2, help_text='Final price paid after discount', max_digits=10)),
                ('payment_bypassed', models.BooleanField(default=False, help_text='True if 100% free - Stripe was bypassed')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address at time of redemption', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent at time of redemption')),
                ('private_lesson_order', models.ForeignKey(blank=True, help_text='Order if used for private lessons', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_redemptions', to='private_teaching.order')),
                ('stripe_payment', models.ForeignKey(blank=True, help_text='Associated Stripe payment if payment was made', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_redemption', to='payments.stripepayment')),
                ('student', models.ForeignKey(help_text='The student who redeemed the voucher', on_delete=django.db.models.deletion.CASCADE, related_name='voucher_redemptions', to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(help_text='The voucher that was redeemed', on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='payments.voucher')),
                ('workshop_registration', models.ForeignKey(blank=True, help_text='Registration if used for workshop', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_redemptions', to='workshops.workshopregistration')),
            ],
            options={
                'verbose_name': 'Voucher Redemption',
                'verbose_name_plural': 'Voucher Redemptions',
                'ordering': ['-redeemed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['code'], name='payments_vo_code_f73524_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['created_by', 'status'], name='payments_vo_created_7345c2_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['valid_from', 'valid_until'], name='payments_vo_valid_f_9ec118_idx'),
        ),
        migrations.AddIndex(
            model_name='voucherredemption',
            index=models.Index(fields=['voucher', 'student'], name='payments_vo_voucher_a191b2_idx'),
        ),
        migrations.AddIndex(
            model_name='voucherredemption',
            index=models.Index(fields=['domain', 'redeemed_at'], name='payments_vo_domain_62d77f_idx'),
        ),
    ]
