# Generated by Django 5.2.9 on 2026-03-26 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_historicalcourseenrollment'),
        ('payments', '0008_add_voucher_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherredemption',
            name='course_enrollment',
            field=models.ForeignKey(blank=True, help_text='Enrollment if used for a course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_redemptions', to='courses.courseenrollment'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='applicable_domains',
            field=models.JSONField(default=list, help_text="List of domains: ['private_teaching', 'workshops', 'workshop_series', 'digital_products']"),
        ),
    ]
