# Generated by Django 5.2.9 on 2026-04-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_products', '0010_add_restricted_to_digital_products'),
        ('payments', '0009_add_course_enrollment_to_voucher_redemption'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='restricted_to_digital_products',
            field=models.ManyToManyField(blank=True, help_text='If set, only valid for these specific digital products', related_name='restricted_vouchers', to='digital_products.digitalproduct'),
        ),
    ]
