# Generated by Django 5.2.7 on 2025-11-26 09:00

import django.db.models.deletion
import django_ckeditor_5.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Category name', max_length=200)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(help_text='Brief description of this category')),
                ('icon', models.CharField(default='fa-solid fa-book-open-reader', help_text='Font Awesome icon class (e.g., "fa-solid fa-graduation-cap")', max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this category on the site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Article title', max_length=300)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('summary', models.TextField(blank=True, help_text='Short summary (optional, shown in listings)')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(help_text='Full article content', verbose_name='content')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_promoted', models.BooleanField(default=False, help_text='Show on help center homepage as promoted article')),
                ('view_count', models.IntegerField(default=0, help_text='Number of times viewed')),
                ('helpful_count', models.IntegerField(default=0, help_text="Number of 'helpful' votes")),
                ('not_helpful_count', models.IntegerField(default=0, help_text="Number of 'not helpful' votes")),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description (optional)', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(help_text='Category this article belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='help_center.category')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='help_center_status_0580aa_idx'), models.Index(fields=['category', 'status'], name='help_center_categor_b30062_idx'), models.Index(fields=['is_promoted', 'status'], name='help_center_is_prom_2de7c5_idx')],
            },
        ),
    ]
