# Generated by Django 5.2.7 on 2025-11-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_center', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='article',
            name='help_center_categor_b30062_idx',
        ),
        migrations.AddField(
            model_name='article',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order within category (lower numbers appear first)'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['category', 'status', 'order'], name='help_center_categor_729e77_idx'),
        ),
    ]
