# Generated by Django 5.2.9 on 2025-12-26 14:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('instructions', models.TextField(help_text='Assignment instructions for students')),
                ('has_notation_component', models.BooleanField(default=True, help_text='Whether this assignment includes a music notation component')),
                ('has_written_component', models.BooleanField(default=False, help_text='Whether this assignment includes written questions')),
                ('written_questions', models.JSONField(blank=True, help_text="Array of written questions: [{question: 'text', type: 'short'|'long'}]", null=True)),
                ('reference_notation', models.JSONField(blank=True, help_text="VexFlow notation data for teacher's reference/example", null=True)),
                ('expected_notation', models.JSONField(blank=True, help_text='Expected notation answer for auto-grading (future feature)', null=True)),
                ('expected_written_answers', models.JSONField(blank=True, help_text='Expected written answers for auto-grading (future feature)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this assignment is available for assignment')),
                ('created_by', models.ForeignKey(help_text='Teacher who created this assignment', on_delete=django.db.models.deletion.CASCADE, related_name='created_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notation_data', models.JSONField(blank=True, help_text='VexFlow notation data created by student', null=True)),
                ('written_answers', models.JSONField(blank=True, help_text="Student's written answers: [{question_index: 0, answer: 'text'}]", null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('graded', 'Graded')], default='draft', max_length=20)),
                ('draft_saved_at', models.DateTimeField(blank=True, help_text='Last time draft was saved', null=True)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When student submitted the assignment', null=True)),
                ('grade', models.DecimalField(blank=True, decimal_places=2, help_text='Grade out of 100', max_digits=5, null=True)),
                ('feedback', models.TextField(blank=True, help_text="Teacher's feedback on the submission")),
                ('graded_at', models.DateTimeField(blank=True, help_text='When teacher graded the submission', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignment')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['created_by', '-created_at'], name='assignments_created_636db3_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['student', 'status'], name='assignments_student_9ba522_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['assignment', 'status'], name='assignments_assignm_bbafe4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assignmentsubmission',
            unique_together={('student', 'assignment')},
        ),
    ]
