# Generated by Django 5.2.9 on 2025-12-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='grading_scale',
            field=models.CharField(choices=[('100', '0-100 Points'), ('10', '0-10 Points'), ('pass_fail', 'Pass/Fail')], default='100', help_text='Grading scale for this assignment', max_length=20),
        ),
    ]
