# Generated by Django 5.2.9 on 2025-12-27 17:41

import django.db.models.deletion
import django_ckeditor_5.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_assignment_grading_scale'),
    ]

    operations = [
        migrations.CreateModel(
            name='WrittenAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_index', models.IntegerField(help_text='Index of the question being answered')),
                ('answer', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text="Student's answer with rich text formatting")),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written_answer_details', to='assignments.assignmentsubmission')),
            ],
            options={
                'ordering': ['question_index'],
                'unique_together': {('submission', 'question_index')},
            },
        ),
    ]
