# Generated by Django 5.2.9 on 2025-12-27 17:46

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_writtenanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='written_response',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text="Student's written response with rich text formatting", null=True),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='written_answers',
            field=models.JSONField(blank=True, help_text='DEPRECATED: Use written_response instead', null=True),
        ),
        migrations.DeleteModel(
            name='WrittenAnswer',
        ),
    ]
