# Generated by Django 5.2.9 on 2025-12-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_assignmentsubmission_written_response_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='expected_written_answers',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='written_questions',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='has_written_component',
            field=models.BooleanField(default=False, help_text='Whether this assignment includes a written response component'),
        ),
    ]
