# Generated by Django 5.2.9 on 2025-12-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_remove_written_questions_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Assignment Tag',
                'verbose_name_plural': 'Assignment Tags',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], help_text='Difficulty level', max_length=20),
        ),
        migrations.AddField(
            model_name='assignment',
            name='is_public',
            field=models.BooleanField(default=False, help_text='If checked, assignment appears in library for browsing by other teachers'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags for categorization (e.g., Scales, Rhythm, Theory)', related_name='assignments', to='assignments.tag'),
        ),
    ]
