# Generated by Django 5.2.9 on 2025-12-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_tag_assignment_difficulty_assignment_is_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='reference_image',
            field=models.ImageField(blank=True, help_text='Upload notation image from Sibelius, Finale, MuseScore, etc. (JPG, PNG, SVG)', null=True, upload_to='assignment_references/'),
        ),
    ]
