# Generated by Django 5.2.9 on 2026-05-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0008_submissionattachment_assignment_has_attachment_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='printable_document',
            field=models.FileField(blank=True, help_text='Upload a worksheet or document for students to print and complete (PDF, JPG, PNG)', null=True, upload_to='assignment_documents/'),
        ),
    ]
