# Generated by Django 5.2.9 on 2026-05-11 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0009_assignment_printable_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionattachment',
            name='round_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('feedback_given', 'Feedback Given'), ('graded', 'Graded')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='FeedbackRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField()),
                ('teacher_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('given_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_feedback_rounds', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='assignments.assignmentsubmission')),
            ],
            options={
                'ordering': ['round_number'],
                'unique_together': {('submission', 'round_number')},
            },
        ),
    ]
