# Generated by Django 5.2.9 on 2026-05-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0010_feedbackround_and_round_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='submission_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of times a student may submit for feedback (leave blank for no limit)', null=True),
        ),
    ]
