# Generated by Django 5.2.7 on 2025-11-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('teacher_application', 'Teacher Application'), ('payment', 'Payment Issue'), ('technical', 'Technical Support'), ('general', 'General Inquiry'), ('bug', 'Bug Report'), ('feature', 'Feature Request')], db_index=True, max_length=20),
        ),
    ]
