# Generated by Django 5.2.7 on 2025-12-11 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_alter_ticket_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketattachment',
            name='file',
            field=models.FileField(help_text='Allowed formats: PDF, images, text, Word (max 10MB)', upload_to='support/attachments/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'txt', 'doc', 'docx'])]),
        ),
    ]
