# Generated by Django 5.2.9 on 2026-04-03 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop_reminders_enabled', models.BooleanField(default=True, help_text='Send reminder emails before workshop sessions')),
                ('workshop_reminder_hours', models.PositiveIntegerField(default=24, help_text='Hours before a workshop session to send reminders (e.g. 24 = 1 day before)')),
                ('lesson_reminders_enabled', models.BooleanField(default=True, help_text='Send reminder emails before private lessons')),
                ('lesson_reminder_hours', models.PositiveIntegerField(default=24, help_text='Hours before a lesson to send reminders (e.g. 24 = 1 day before)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reminder Settings',
                'verbose_name_plural': 'Reminder Settings',
                'db_table': 'scheduling_reminder_settings',
            },
        ),
    ]
