# Generated by Django 4.2.28 on 2026-02-23 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0016_userprofile_workshop_email_notifications'),
        ('private_teaching', '0038_remove_quiz_models'),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalExamRegistration',
            fields=[
                ('payment_status', models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending Payment'), ('completed', 'Payment Completed'), ('failed', 'Payment Failed')], default='not_required', help_text='Current payment status', max_length=20)),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount paid or to be paid', max_digits=10)),
                ('stripe_payment_intent_id', models.CharField(blank=True, help_text='Stripe PaymentIntent ID for tracking', max_length=255)),
                ('stripe_checkout_session_id', models.CharField(blank=True, help_text='Stripe Checkout Session ID', max_length=255)),
                ('paid_at', models.DateTimeField(blank=True, help_text='Timestamp when payment was completed', null=True)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('grade_type', models.CharField(choices=[('practical', 'Practical Grade'), ('performance', 'Performance Grade'), ('theory', 'Music Theory')], help_text='Type of exam (Practical, Performance, or Theory)', max_length=20)),
                ('grade_level', models.PositiveIntegerField(help_text='Grade level (1-8 for Practical/Performance, 1-6 for Theory)')),
                ('exam_date', models.DateField(blank=True, help_text='Date of the exam', null=True)),
                ('submission_deadline', models.DateField(blank=True, help_text='Deadline for submitting recordings/videos', null=True)),
                ('registration_number', models.CharField(blank=True, help_text='Registration number from the exam board', max_length=100)),
                ('venue', models.CharField(blank=True, help_text='Exam venue or submission method', max_length=200)),
                ('scales', models.TextField(blank=True, help_text='Required scales')),
                ('arpeggios', models.TextField(blank=True, help_text='Required arpeggios')),
                ('sight_reading', models.TextField(blank=True, help_text='Sight reading requirements or notes')),
                ('aural_tests', models.TextField(blank=True, help_text='Aural test requirements or notes')),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('submitted', 'Exam Submitted'), ('results_received', 'Results Received')], default='registered', help_text='Current exam status', max_length=20)),
                ('mark_achieved', models.PositiveIntegerField(blank=True, help_text='Numerical mark achieved', null=True)),
                ('grade_achieved', models.CharField(blank=True, choices=[('pass', 'Pass'), ('merit', 'Merit'), ('distinction', 'Distinction'), ('fail', 'Fail')], help_text='Grade achieved', max_length=20)),
                ('examiner_comments', models.TextField(blank=True, help_text='Comments from the examiner')),
                ('certificate_received_date', models.DateField(blank=True, help_text='Date when certificate was received', null=True)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Exam registration fee set by teacher', max_digits=8)),
                ('teacher_notes', models.TextField(blank=True, help_text='Private teacher notes about this exam')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('child_profile', models.ForeignKey(blank=True, db_constraint=False, help_text='If for a child, link to their child profile', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.childprofile')),
                ('exam_board', models.ForeignKey(blank=True, db_constraint=False, help_text='Examination board', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='exams.examboard')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, db_constraint=False, help_text='For adults: the student. For children: the guardian/parent.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, db_constraint=False, help_text='Subject/instrument for the exam', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='private_teaching.subject')),
                ('teacher', models.ForeignKey(blank=True, db_constraint=False, help_text='Teacher registering the student for the exam', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Exam Registration',
                'verbose_name_plural': 'historical Exam Registrations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
