# Generated by Django 5.2.7 on 2025-11-07 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0006_course_expected_launch_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('svg_image', models.FileField(blank=True, help_text='Sheet music or notation image (SVG/PNG/JPG)', null=True, upload_to='audioplayer/svg_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Playalong Piece',
                'verbose_name_plural': 'Playalong Pieces',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='LessonPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order within this specific lesson')),
                ('is_visible', models.BooleanField(default=True, help_text='Show/hide this piece in the lesson')),
                ('instructions', models.TextField(blank=True, help_text='Custom instructions for this piece in this lesson')),
                ('is_optional', models.BooleanField(default=False, help_text='Mark as optional practice')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_pieces', to='courses.lesson')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_assignments', to='audioplayer.piece')),
            ],
            options={
                'verbose_name': 'Lesson Piece Assignment',
                'verbose_name_plural': 'Lesson Piece Assignments',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Stem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_name', models.CharField(help_text='e.g., Piano, Metronome, Backing Track, Recorder', max_length=100)),
                ('audio_file', models.FileField(help_text='MP3 audio file', upload_to='audioplayer/stems/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stems', to='audioplayer.piece')),
            ],
            options={
                'verbose_name': 'Audio Stem',
                'verbose_name_plural': 'Audio Stems',
                'ordering': ['order', 'instrument_name'],
            },
        ),
    ]
