# Generated by Django 5.2.7 on 2025-12-10 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioplayer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('bio', models.TextField(blank=True, help_text='Optional biographical information')),
                ('period', models.CharField(blank=True, help_text='e.g., Baroque, Classical, Romantic, Traditional, Contemporary', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Composer',
                'verbose_name_plural': 'Composers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='piece',
            name='description',
            field=models.TextField(blank=True, help_text='Notes about the piece, performance tips, or context'),
        ),
        migrations.AddField(
            model_name='piece',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], help_text='Difficulty level', max_length=20),
        ),
        migrations.AddField(
            model_name='piece',
            name='genre',
            field=models.CharField(blank=True, choices=[('classical', 'Classical'), ('folk', 'Folk/Traditional'), ('pop', 'Popular'), ('jazz', 'Jazz'), ('baroque', 'Baroque'), ('renaissance', 'Renaissance'), ('contemporary', 'Contemporary'), ('other', 'Other')], help_text='Musical genre or style', max_length=50),
        ),
        migrations.AddField(
            model_name='piece',
            name='grade_level',
            field=models.CharField(blank=True, choices=[('N/A', 'N/A'), ('grade_1', 'Grade 1'), ('grade_2', 'Grade 2'), ('grade_3', 'Grade 3'), ('grade_4', 'Grade 4'), ('grade_5', 'Grade 5'), ('grade_6', 'Grade 6'), ('grade_7', 'Grade 7'), ('grade_8', 'Grade 8')], default='N/A', help_text='Associated exam grade level (optional)', max_length=20),
        ),
        migrations.AddField(
            model_name='piece',
            name='is_public',
            field=models.BooleanField(default=True, help_text='If checked, piece appears in library for all students to browse'),
        ),
        migrations.AddField(
            model_name='piece',
            name='composer',
            field=models.ForeignKey(blank=True, help_text='Composer or artist', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pieces', to='audioplayer.composer'),
        ),
        migrations.AddField(
            model_name='piece',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Additional categorization (e.g., Christmas, Duet, etc.)', related_name='pieces', to='audioplayer.tag'),
        ),
    ]
