# Generated by Django 5.2.7 on 2025-12-10 04:28

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audioplayer', '0002_composer_tag_piece_description_piece_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composer',
            name='bio',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Biographical information with formatting (paragraphs, lists, links, etc.)', verbose_name='biography'),
        ),
    ]
