# Generated by Django 5.2.7 on 2025-12-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioplayer', '0003_alter_composer_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='pdf_score',
            field=models.FileField(blank=True, help_text='Printable PDF version of the score', null=True, upload_to='audioplayer/pdf_scores/'),
        ),
        migrations.AddField(
            model_name='piece',
            name='pdf_score_title',
            field=models.CharField(blank=True, help_text="Descriptive title for the PDF score (e.g., 'Full Score with Piano Accompaniment')", max_length=200),
        ),
        migrations.AlterField(
            model_name='piece',
            name='svg_image',
            field=models.FileField(blank=True, help_text='Sheet music or notation image (SVG/PNG/JPG) for on-screen display', null=True, upload_to='audioplayer/svg_images/'),
        ),
    ]
