# Generated by Django 5.2.7 on 2025-12-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioplayer', '0004_piece_pdf_score_piece_pdf_score_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='composer',
            name='dates',
            field=models.CharField(blank=True, help_text="Birth and death dates (e.g., '1685-1750' or 'c.1547 - c.1601')", max_length=100),
        ),
    ]
