# Generated by Django 5.2.7 on 2025-12-23 14:04

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioplayer', '0005_composer_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='pdf_score',
            field=models.FileField(blank=True, help_text='Printable PDF version of the score (max 5MB)', null=True, upload_to='audioplayer/pdf_scores/', validators=[django.core.validators.FileExtensionValidator(['pdf']), apps.core.validators.FileSizeValidator(max_size_mb=5)]),
        ),
        migrations.AlterField(
            model_name='piece',
            name='svg_image',
            field=models.FileField(blank=True, help_text='Sheet music or notation image (SVG/PNG/JPG) for on-screen display (max 5MB)', null=True, upload_to='audioplayer/svg_images/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'jpeg']), apps.core.validators.FileSizeValidator(max_size_mb=5)]),
        ),
        migrations.AlterField(
            model_name='stem',
            name='audio_file',
            field=models.FileField(help_text='MP3 or WAV audio file (max 10MB)', upload_to='audioplayer/stems/', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav']), apps.core.validators.FileSizeValidator(max_size_mb=10)]),
        ),
    ]
