# Generated by Django 5.2.7 on 2025-12-24 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioplayer', '0006_alter_piece_pdf_score_alter_piece_svg_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Teacher who created this piece', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pieces', to=settings.AUTH_USER_MODEL),
        ),
    ]
