# Generated by Django 5.2.9 on 2026-01-25 13:26

import apps.core.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioplayer', '0007_piece_created_by'),
        ('courses', '0020_add_content_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='piece',
            options={'ordering': ['order_in_collection', 'title'], 'verbose_name': 'Playalong Piece', 'verbose_name_plural': 'Playalong Pieces'},
        ),
        migrations.AddField(
            model_name='piece',
            name='order_in_collection',
            field=models.PositiveIntegerField(default=0, help_text='Display order within the collection'),
        ),
        migrations.CreateModel(
            name='PieceCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Collection title (e.g., 'Syncopation Exercises Grade 2')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the collection, learning objectives, etc.')),
                ('pdf_score', models.FileField(blank=True, help_text='Full score PDF containing all exercises (max 5MB)', null=True, upload_to='audioplayer/collection_pdfs/', validators=[django.core.validators.FileExtensionValidator(['pdf']), apps.core.validators.FileSizeValidator(max_size_mb=5)])),
                ('pdf_score_title', models.CharField(blank=True, help_text="Title for the PDF download (e.g., 'Complete Worksheet')", max_length=200)),
                ('grade_level', models.CharField(blank=True, choices=[('N/A', 'N/A'), ('grade_1', 'Grade 1'), ('grade_2', 'Grade 2'), ('grade_3', 'Grade 3'), ('grade_4', 'Grade 4'), ('grade_5', 'Grade 5'), ('grade_6', 'Grade 6'), ('grade_7', 'Grade 7'), ('grade_8', 'Grade 8')], default='N/A', help_text='Associated exam grade level', max_length=20)),
                ('genre', models.CharField(blank=True, choices=[('classical', 'Classical'), ('folk', 'Folk/Traditional'), ('pop', 'Popular'), ('jazz', 'Jazz'), ('baroque', 'Baroque'), ('renaissance', 'Renaissance'), ('contemporary', 'Contemporary'), ('other', 'Other')], help_text='Musical genre or style', max_length=50)),
                ('difficulty', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], help_text='Overall difficulty level', max_length=20)),
                ('is_public', models.BooleanField(default=True, help_text='If checked, collection appears in library for all students')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('composer', models.ForeignKey(blank=True, help_text='Composer or arranger (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to='audioplayer.composer')),
                ('created_by', models.ForeignKey(blank=True, help_text='Teacher who created this collection', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_collections', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, help_text='Tags for categorization', related_name='collections', to='audioplayer.tag')),
            ],
            options={
                'verbose_name': 'Piece Collection',
                'verbose_name_plural': 'Piece Collections',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='LessonCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order within this specific lesson')),
                ('is_visible', models.BooleanField(default=True, help_text='Show/hide this collection in the lesson')),
                ('instructions', models.TextField(blank=True, help_text='Custom instructions for this collection in this lesson')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_collections', to='courses.lesson')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_assignments', to='audioplayer.piececollection')),
            ],
            options={
                'verbose_name': 'Lesson Collection Assignment',
                'verbose_name_plural': 'Lesson Collection Assignments',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='piece',
            name='collection',
            field=models.ForeignKey(blank=True, help_text='Collection this piece belongs to (leave empty for standalone pieces)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pieces', to='audioplayer.piececollection'),
        ),
    ]
