# Generated by Django 5.2.9 on 2026-01-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioplayer', '0009_refactor_collection_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='show_in_library',
            field=models.BooleanField(default=True, help_text="If unchecked, piece won't appear individually in library (useful for pieces only accessed via collections)"),
        ),
    ]
