# Generated by Django 5.2.9 on 2026-02-13 16:38

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioplayer', '0010_add_show_in_library_to_piece'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stem',
            name='audio_file',
            field=models.FileField(help_text='MP3 or WAV audio file (max 15MB)', upload_to='audioplayer/stems/', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav']), apps.core.validators.FileSizeValidator(max_size_mb=15)]),
        ),
    ]
