# Generated by Django 5.2.7 on 2025-10-25 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workshops', '0010_alter_workshopregistration_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of this category')),
                ('is_active', models.BooleanField(default=True, help_text="Inactive categories won't appear in expense form")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_categories_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Expense Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date the expense was incurred')),
                ('business_area', models.CharField(choices=[('private_teaching', 'Private Teaching'), ('workshops', 'Workshops'), ('courses', 'Courses')], max_length=20)),
                ('description', models.TextField(help_text='What was purchased')),
                ('supplier', models.CharField(help_text='Vendor or supplier name', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in GBP (£)', max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal'), ('other', 'Other')], default='card', max_length=20)),
                ('receipt_file', models.FileField(blank=True, help_text='Upload receipt image or PDF', null=True, upload_to='expense_receipts/')),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_created', to=settings.AUTH_USER_MODEL)),
                ('workshop', models.ForeignKey(blank=True, help_text='Link to specific workshop (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='workshops.workshop')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expenses.expensecategory')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['-date'], name='expenses_ex_date_2850f8_idx'), models.Index(fields=['business_area'], name='expenses_ex_busines_befcf7_idx'), models.Index(fields=['category'], name='expenses_ex_categor_20264a_idx')],
            },
        ),
    ]
