# Generated by Django 5.2.7 on 2025-10-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='business_area',
            field=models.CharField(choices=[('private_teaching', 'Private Teaching'), ('workshops', 'Workshops'), ('courses', 'Courses'), ('general', 'General/Shared Expenses')], max_length=20),
        ),
    ]
