# Generated by Django 5.2.7 on 2025-12-11 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expense_business_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='receipt_file',
            field=models.FileField(blank=True, help_text='Upload receipt image or PDF (max 5MB)', null=True, upload_to='expense_receipts/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
