# Generated by Django 5.2.7 on 2025-12-21 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_expense_receipt_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='business_area',
            field=models.CharField(choices=[('private_teaching', 'Private Teaching'), ('workshops', 'Workshops'), ('courses', 'Courses'), ('digital_products', 'Digital Products'), ('general', 'General/Shared Expenses')], max_length=20),
        ),
    ]
