# Generated by Django 5.2.7 on 2025-10-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='zoom_link',
            field=models.URLField(blank=True, default='', help_text='Zoom meeting link for online lessons'),
        ),
    ]
