# Generated by Django 5.2.7 on 2025-11-12 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioplayer', '0001_initial'),
        ('lessons', '0004_alter_lesson_lesson_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateLessonPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within the lesson')),
                ('is_visible', models.BooleanField(default=True, help_text='Whether students can see this piece')),
                ('instructions', models.TextField(blank=True, help_text='Lesson-specific instructions for this piece')),
                ('is_optional', models.BooleanField(default=False, help_text='Whether this piece is optional practice')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(help_text='The lesson this piece is assigned to', on_delete=django.db.models.deletion.CASCADE, related_name='lesson_pieces', to='lessons.lesson')),
                ('piece', models.ForeignKey(help_text='The playalong piece', on_delete=django.db.models.deletion.CASCADE, related_name='private_lesson_assignments', to='audioplayer.piece')),
            ],
            options={
                'verbose_name': 'Lesson Piece',
                'verbose_name_plural': 'Lesson Pieces',
                'ordering': ['order', 'created_at'],
                'unique_together': {('lesson', 'piece')},
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='pieces',
            field=models.ManyToManyField(blank=True, help_text='Interactive playalong pieces for this lesson', related_name='private_lessons', through='lessons.PrivateLessonPiece', to='audioplayer.piece'),
        ),
    ]
