# Generated by Django 5.2.7 on 2025-11-15 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_add_playalong_pieces'),
        ('private_teaching', '0008_examboard_examregistration_exampiece_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='exam_registration',
            field=models.ForeignKey(blank=True, help_text='Link to exam if this lesson is for exam preparation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preparation_lessons', to='private_teaching.examregistration'),
        ),
    ]
