# Generated by Django 5.2.9 on 2025-12-27 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_assignment_grading_scale'),
        ('lessons', '0006_lesson_exam_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateTimeField(blank=True, help_text='When this assignment is due (defaults to next lesson)', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within homework list')),
                ('instructions', models.TextField(blank=True, help_text='Lesson-specific instructions for this assignment')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(help_text='The homework assignment', on_delete=django.db.models.deletion.CASCADE, related_name='lesson_assignments', to='assignments.assignment')),
                ('lesson', models.ForeignKey(help_text='The lesson this assignment is homework for', on_delete=django.db.models.deletion.CASCADE, related_name='lesson_assignments', to='lessons.lesson')),
            ],
            options={
                'verbose_name': 'Lesson Assignment',
                'verbose_name_plural': 'Lesson Assignments',
                'ordering': ['order', 'assigned_at'],
                'unique_together': {('lesson', 'assignment')},
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='assignments',
            field=models.ManyToManyField(blank=True, help_text='Homework assignments for this lesson', related_name='lessons', through='lessons.LessonAssignment', to='assignments.assignment'),
        ),
    ]
