# Generated by Django 5.2.9 on 2025-12-27
# Custom migration to convert LessonAssignment ID from integer to UUID

import django.db.models.deletion
import uuid
from django.db import migrations, models


def delete_existing_assignments(apps, schema_editor):
    """Delete all existing LessonAssignment records before converting ID field"""
    LessonAssignment = apps.get_model('lessons', 'LessonAssignment')
    count = LessonAssignment.objects.count()
    LessonAssignment.objects.all().delete()
    if count > 0:
        print(f'Deleted {count} existing LessonAssignment records')


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_add_lesson_assignments'),
    ]

    operations = [
        # First, delete all existing records
        migrations.RunPython(delete_existing_assignments, migrations.RunPython.noop),

        # Then alter the ID field to UUID
        migrations.AlterField(
            model_name='lessonassignment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
