# Generated by Django 5.2.9 on 2025-12-27 19:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_convert_lessonassignment_to_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonassignment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
