# Generated by Django 5.2.9 on 2026-01-04 20:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0007_assignment_reference_image'),
        ('audioplayer', '0007_piece_created_by'),
        ('lessons', '0009_alter_lessonassignment_id'),
        ('private_teaching', '0023_add_max_recurring_lessons'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['teacher', 'lesson_date', 'is_deleted'], name='lesson_teacher_schedule_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['payment_status', 'approved_status'], name='lesson_payment_status_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['lesson_date', 'lesson_time'], name='lesson_datetime_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['student', 'is_deleted', 'lesson_date'], name='lesson_student_schedule_idx'),
        ),
    ]
