# Generated by Django 5.2.9 on 2026-01-25 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioplayer', '0008_add_piece_collections'),
        ('lessons', '0010_lesson_lesson_teacher_schedule_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateLessonCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within the lesson')),
                ('is_visible', models.BooleanField(default=True, help_text='Whether students can see this collection')),
                ('instructions', models.TextField(blank=True, help_text='Lesson-specific instructions for this collection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(help_text='The piece collection', on_delete=django.db.models.deletion.CASCADE, related_name='private_lesson_assignments', to='audioplayer.piececollection')),
                ('lesson', models.ForeignKey(help_text='The lesson this collection is assigned to', on_delete=django.db.models.deletion.CASCADE, related_name='lesson_collections', to='lessons.lesson')),
            ],
            options={
                'verbose_name': 'Lesson Collection',
                'verbose_name_plural': 'Lesson Collections',
                'ordering': ['order', 'created_at'],
                'unique_together': {('lesson', 'collection')},
            },
        ),
    ]
