# Generated by Django 5.2.9 on 2026-02-23 08:36

from django.db import migrations


LESSON_VALUE_MAP = {
    'Not Paid': 'pending',
    'Payment In Process': 'pending',
    'Paid': 'completed',
    'Failed': 'failed',
}

LESSONORDER_VALUE_MAP = {
    'NONE': 'not_required',
    'Payment In Process': 'pending',
    'Paid': 'completed',
    'Failed': 'failed',
}


def convert_lesson_payment_status(apps, schema_editor):
    Lesson = apps.get_model('lessons', 'Lesson')
    for old, new in LESSON_VALUE_MAP.items():
        Lesson.objects.filter(payment_status=old).update(payment_status=new)


def revert_lesson_payment_status(apps, schema_editor):
    Lesson = apps.get_model('lessons', 'Lesson')
    reverse_map = {v: k for k, v in LESSON_VALUE_MAP.items()}
    for old, new in reverse_map.items():
        Lesson.objects.filter(payment_status=old).update(payment_status=new)


def convert_lessonorder_payment_status(apps, schema_editor):
    LessonOrder = apps.get_model('lessons', 'LessonOrder')
    for old, new in LESSONORDER_VALUE_MAP.items():
        LessonOrder.objects.filter(payment_status=old).update(payment_status=new)


def revert_lessonorder_payment_status(apps, schema_editor):
    LessonOrder = apps.get_model('lessons', 'LessonOrder')
    reverse_map = {v: k for k, v in LESSONORDER_VALUE_MAP.items()}
    for old, new in reverse_map.items():
        LessonOrder.objects.filter(payment_status=old).update(payment_status=new)


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0012_alter_lesson_payment_status_and_more'),
    ]

    operations = [
        migrations.RunPython(
            convert_lesson_payment_status,
            revert_lesson_payment_status,
        ),
        migrations.RunPython(
            convert_lessonorder_payment_status,
            revert_lessonorder_payment_status,
        ),
    ]
