# Generated by Django 5.2.9 on 2026-02-23 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_userprofile_workshop_email_notifications'),
        ('assignments', '0007_assignment_reference_image'),
        ('lessons', '0013_convert_payment_status_values'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lessonassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='lessonassignment',
            name='child_profile',
            field=models.ForeignKey(blank=True, help_text='Optional: specific child this assignment is for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_assignments_received', to='accounts.childprofile'),
        ),
        migrations.AddField(
            model_name='lessonassignment',
            name='student',
            field=models.ForeignKey(blank=True, help_text='Student (standalone only; lesson-linked derive from lesson.student)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standalone_assignments_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonassignment',
            name='teacher',
            field=models.ForeignKey(blank=True, help_text='Teacher (standalone only; lesson-linked derive from lesson.subject.teacher)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standalone_assignments_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lessonassignment',
            name='lesson',
            field=models.ForeignKey(blank=True, help_text='The lesson this assignment is homework for (null for standalone)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_assignments', to='lessons.lesson'),
        ),
        migrations.AddConstraint(
            model_name='lessonassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('lesson__isnull', False)), fields=('lesson', 'assignment'), name='unique_lesson_assignment_per_lesson'),
        ),
    ]
