# Generated by Django 4.2.28 on 2026-02-23 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0002_historicalexamregistration'),
        ('private_teaching', '0038_remove_quiz_models'),
        ('lessons', '0015_update_exam_registration_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalLesson',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('duration_in_minutes', models.CharField(choices=[('30', '30'), ('60', '60'), ('90', '90')], default='60', max_length=7)),
                ('lesson_date', models.DateField()),
                ('lesson_time', models.TimeField()),
                ('fee', models.FloatField(blank=True, help_text='Calculated lesson price', null=True)),
                ('location', models.CharField(choices=[('Online', 'Online'), ('Onsite', 'Onsite')], default='Online', max_length=20)),
                ('attendance', models.CharField(choices=[('Attended', 'Attended'), ('No-show', 'No-show'), ('Legal-Cancel', 'Legal-Cancel'), ('Illegal-Cancel', 'Illegal-Cancel')], default='Attended', max_length=20)),
                ('zoom_link', models.URLField(blank=True, default='', help_text='Zoom meeting link for online lessons')),
                ('lesson_content', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('teacher_notes', models.TextField(blank=True, null=True)),
                ('homework', models.TextField(blank=True, null=True)),
                ('private_note', models.TextField(blank=True, help_text='Private notes not visible to students', null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Assigned', 'Assigned')], default='Draft', max_length=20)),
                ('approved_status', models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending Payment'), ('completed', 'Payment Completed'), ('failed', 'Payment Failed')], default='pending', max_length=20)),
                ('in_cart', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag for rejected lessons')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('exam_registration', models.ForeignKey(blank=True, db_constraint=False, help_text='Link to exam if this lesson is for exam preparation', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='exams.examregistration')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lesson_request', models.ForeignKey(blank=True, db_constraint=False, help_text='The lesson request this lesson belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='private_teaching.lessonrequest')),
                ('student', models.ForeignKey(blank=True, db_constraint=False, help_text='Student taking this lesson', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='private_teaching.subject')),
                ('teacher', models.ForeignKey(blank=True, db_constraint=False, help_text='Teacher giving this lesson (auto-populated from subject)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical lesson',
                'verbose_name_plural': 'historical lessons',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
