# Generated by Django 5.2.9 on 2026-06-06 13:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0017_standaloneDocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StandaloneUrl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('description', models.CharField(blank=True, help_text="Optional note, e.g. 'Warm-up exercises — start at 2:30'", max_length=500)),
                ('share_with_all_students', models.BooleanField(default=True, help_text='Make available to all current students')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('shared_with_students', models.ManyToManyField(blank=True, help_text='Specific students to share with (only used when not sharing with all)', related_name='shared_standalone_urls', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standalone_urls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
