# Generated by Django 5.2.9 on 2026-07-04 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_userprofile_lesson_reminder_notifications'),
        ('lessons', '0018_standalone_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='standalonedocument',
            name='child_profile',
            field=models.ForeignKey(blank=True, help_text='The specific child this resource is for (its primary target), when shared with a child student', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standalone_documents', to='accounts.childprofile'),
        ),
        migrations.AddField(
            model_name='standaloneurl',
            name='child_profile',
            field=models.ForeignKey(blank=True, help_text='The specific child this resource is for (its primary target), when shared with a child student', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standalone_urls', to='accounts.childprofile'),
        ),
    ]
