# Generated by Django 5.2.7 on 2025-12-20 19:50

import django.core.validators
import django.db.models.deletion
import django_ckeditor_5.fields
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0016_userprofile_workshop_email_notifications'),
        ('private_teaching', '0017_make_cancellation_fields_optional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='CSS icon class or emoji (e.g., 🎼, 📄)', max_length=50)),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color code for UI display', max_length=7)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Product Categories',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='digital_pro_is_acti_d1305b_idx')],
            },
        ),
        migrations.CreateModel(
            name='DigitalProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='description')),
                ('short_description', models.CharField(max_length=300)),
                ('product_type', models.CharField(choices=[('sheet_music', 'Sheet Music (PDF)'), ('practice_materials', 'Practice Materials (PDF)'), ('video', 'Video Recording'), ('audio', 'Audio File'), ('research', 'Research Article/Paper (PDF)'), ('bundle', 'Bundle (Multiple Files)')], max_length=30)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags (e.g., baroque, intermediate, ensemble)', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('featured_image', models.ImageField(blank=True, help_text='Product thumbnail (recommended: 1200x800px)', null=True, upload_to='digital_products/images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('total_sales', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_products', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='digital_products.productcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title/name of the attachment', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(help_text='Main product file (max 50MB)', upload_to='digital_products/files/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'zip', 'mp3', 'mp4', 'wav', 'flac', 'avi', 'mov'])])),
                ('file_role', models.CharField(choices=[('main', 'Main Product File'), ('preview', 'Preview/Sample File'), ('bonus', 'Bonus Content')], default='main', help_text='Role of this file (main product, preview, or bonus content)', max_length=20)),
                ('file_size_bytes', models.BigIntegerField(default=0, help_text='File size in bytes (auto-calculated)')),
                ('download_limit', models.PositiveIntegerField(default=5, help_text='Maximum downloads per purchase')),
                ('access_duration_days', models.PositiveIntegerField(default=30, help_text='Days after purchase before link expires')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='digital_products.digitalproduct')),
            ],
            options={
                'ordering': ['order', 'file_role', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProductPurchase',
            fields=[
                ('payment_status', models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending Payment'), ('completed', 'Payment Completed'), ('failed', 'Payment Failed')], default='not_required', help_text='Current payment status', max_length=20)),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount paid or to be paid', max_digits=10)),
                ('stripe_payment_intent_id', models.CharField(blank=True, help_text='Stripe PaymentIntent ID for tracking', max_length=255)),
                ('stripe_checkout_session_id', models.CharField(blank=True, help_text='Stripe Checkout Session ID', max_length=255)),
                ('paid_at', models.DateTimeField(blank=True, help_text='Timestamp when payment was completed', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('download_counts', models.JSONField(blank=True, default=dict, help_text='Track download count per file: {file_id: count}')),
                ('access_expires_at', models.DateTimeField(help_text='When download access expires (typically 30 days after purchase)')),
                ('child_profile', models.ForeignKey(blank=True, help_text='If for a child, link to their child profile', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.childprofile')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='digital_products.digitalproduct')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_product_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-purchased_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveIntegerField(help_text='Rating from 1-5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(max_length=200)),
                ('comment', models.TextField()),
                ('is_verified_purchase', models.BooleanField(default=True, help_text='Always true since review is linked to purchase')),
                ('is_published', models.BooleanField(default=True, help_text='Unpublish for moderation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='digital_products.digitalproduct')),
                ('purchase', models.OneToOneField(help_text='Link to purchase (ensures only purchasers can review)', on_delete=django.db.models.deletion.CASCADE, related_name='review', to='digital_products.productpurchase')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_product_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DigitalProductCartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price when added to cart (frozen)', max_digits=10)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_product_items', to='private_teaching.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digital_products.digitalproduct')),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('cart', 'product')},
            },
        ),
        migrations.AddIndex(
            model_name='digitalproduct',
            index=models.Index(fields=['status', 'teacher'], name='digital_pro_status_5a7ee1_idx'),
        ),
        migrations.AddIndex(
            model_name='digitalproduct',
            index=models.Index(fields=['category', 'status'], name='digital_pro_categor_672c94_idx'),
        ),
        migrations.AddIndex(
            model_name='digitalproduct',
            index=models.Index(fields=['product_type', 'status'], name='digital_pro_product_c7f7b7_idx'),
        ),
        migrations.AddIndex(
            model_name='digitalproduct',
            index=models.Index(fields=['slug'], name='digital_pro_slug_9bcab0_idx'),
        ),
        migrations.AddIndex(
            model_name='productpurchase',
            index=models.Index(fields=['student', 'payment_status'], name='digital_pro_student_71be73_idx'),
        ),
        migrations.AddIndex(
            model_name='productpurchase',
            index=models.Index(fields=['product', 'payment_status'], name='digital_pro_product_f60349_idx'),
        ),
        migrations.AddIndex(
            model_name='productpurchase',
            index=models.Index(fields=['access_expires_at'], name='digital_pro_access__4636ac_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productpurchase',
            unique_together={('student', 'product')},
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['product', 'is_published'], name='digital_pro_product_76319f_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['rating', 'created_at'], name='digital_pro_rating_45167b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productreview',
            unique_together={('student', 'product')},
        ),
    ]
