# Generated by Django 5.2.7 on 2025-12-21 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='productpurchase',
            name='digital_pro_access__4636ac_idx',
        ),
        migrations.AlterField(
            model_name='productfile',
            name='access_duration_days',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='DEPRECATED: No longer enforced. Kept for historical data.', null=True),
        ),
        migrations.AlterField(
            model_name='productfile',
            name='download_limit',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='DEPRECATED: No longer enforced. Kept for historical data.', null=True),
        ),
        migrations.AlterField(
            model_name='productpurchase',
            name='access_expires_at',
            field=models.DateTimeField(blank=True, help_text='DEPRECATED: No longer enforced. Users have lifetime access.', null=True),
        ),
        migrations.AlterField(
            model_name='productpurchase',
            name='download_counts',
            field=models.JSONField(blank=True, default=dict, help_text='DEPRECATED: No longer tracked. Kept for historical data.'),
        ),
    ]
