# Generated by Django 5.2.9 on 2025-12-28 18:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_products', '0002_remove_productpurchase_digital_pro_access__4636ac_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfile',
            name='content_type',
            field=models.CharField(choices=[('file', 'Uploaded File'), ('url', 'External URL')], default='file', help_text='Automatically set based on whether file or URL is provided', max_length=10),
        ),
        migrations.AddField(
            model_name='productfile',
            name='content_url',
            field=models.URLField(blank=True, help_text='URL to external content (e.g., private YouTube video, Vimeo, etc.)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='productfile',
            name='file',
            field=models.FileField(blank=True, help_text='Upload a file (max 50MB) OR provide a URL below', null=True, upload_to='digital_products/files/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'zip', 'mp3', 'mp4', 'wav', 'flac', 'avi', 'mov'])]),
        ),
    ]
