# Generated by Django 5.2.9 on 2026-04-23 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital_products', '0010_add_restricted_to_digital_products'),
        ('digital_products', '0010_alter_digitalproductcollection_id_and_more'),
    ]

    operations = [
    ]
